import { Economy, PROPERTIES, INFRA, STAGES, format, type PropertyId, type InfraId } from '../simulation/economy';
import type { Player } from '../player/controller';
import type { City, Target } from '../world/city';
import type { Soundscape } from '../audio/sound';
const crest = `<svg viewBox="0 0 40 48" aria-hidden="true"><path d="M4 3h32v26L20 44 4 29z"/><path d="M11 13h18m-9 0v20M13 19h14"/></svg>`;
export class Interface {
  app = document.querySelector<HTMLDivElement>('#app')!; started = false; panel: string | null = null; tab = 'Properties'; selected: PropertyId | null = null; tracked: PropertyId | null = 'scrap'; confirmReset = false; toastTimer = 0;
  onStart: () => void = () => {}; onReset: () => void = () => {}; onQuality: () => void = () => {};
  constructor(public economy: Economy, public player: Player, public city: City, public sound: Soundscape) { this.app.innerHTML = `
    <div class="vignette"></div><header id="hud"><div class="identity">${crest}<div><b>CITY TYCOON</b><span>TERRA <i> / </i> LOCKE</span></div></div><div class="bearing"><span id="compass">N</span><small id="weather">DRIZZLE · DUSK</small></div><div class="treasury"><span class="coin">♜</span><div><small>CITY TREASURY</small><strong id="crowns">35</strong></div><div class="income"><b id="rate">+0</b><small>CROWNS / SEC</small></div></div></header>
    <div id="crosshair"></div><div id="interaction" hidden></div><div id="tracked" hidden></div><div id="toast" role="status"></div>
    <footer id="hud-bottom"><div class="objective"><span class="overline">A CITY WORTH SAVING</span><p id="objective">Inspect the old Scrap Yard.</p><small id="stage">00 / THE LOWWORKS</small></div><div class="controls"><span><kbd>W A S D</kbd> Walk</span><span><kbd>E</kbd> Interact</span><span><kbd>⇧</kbd> Sprint</span><span><kbd>TAB</kbd> City ledger</span></div></footer>
    <section id="welcome" class="welcome"><div class="eyebrow"><span></span> WORLD OF LOCKE · CHAPTER I</div><h1>A city of iron.<br>A future <em>in your hands.</em></h1><p>The engines are failing. The lamps are going dark.<br>Terra has one last steward. Make every crown count.</p><button id="enter" class="primary">${economy.state.playtime > 1 ? 'Continue stewardship' : 'Enter the Lowworks'} <span>↗</span></button><div class="welcome-foot">FIRST-PERSON CITY TYCOON <i>•</i> HEADPHONES RECOMMENDED</div></section>
    <section id="pause" class="pause" hidden><div class="eyebrow">THE CITY KEEPS TURNING</div><h2>Take a breath.</h2><p>Your businesses continue working while you’re here.</p><button data-action="resume" class="primary">Return to Terra <span>↗</span></button><button data-action="ledger" class="plain">Open city ledger <kbd>TAB</kbd></button><button data-action="settings" class="plain">Settings</button></section>
    <aside id="panel" class="panel" hidden aria-label="City ledger"></aside><div id="debug" hidden></div><div id="save-status" role="status"></div>`;
    document.querySelector('#enter')!.addEventListener('click', () => this.start());
    this.app.addEventListener('click', e => { const button = (e.target as HTMLElement).closest<HTMLElement>('[data-action]'); if (button && !button.hasAttribute('disabled')) this.action(button.dataset.action!, button.dataset.id ?? ''); });
    this.app.addEventListener('input', e => { const input = e.target as HTMLInputElement; const key = input.dataset.setting; if (!key) return; const s = this.economy.state.settings; if (key === 'reducedMotion') s.reducedMotion = input.checked; else if (['master', 'ambience', 'sfx', 'music', 'sensitivity'].includes(key)) (s as unknown as Record<string, number>)[key] = Number(input.value); this.sound.apply(); this.economy.save(); });
    document.addEventListener('keydown', e => { if (!this.started || e.repeat) return; if (e.code === 'Tab') { e.preventDefault(); if (this.panel) this.close(true); else this.openLedger(); } if (e.code === 'Escape' && this.panel) this.close(false); });
    player.onInteract = t => this.interact(t); player.onLock = locked => { document.querySelector('#pause')!.toggleAttribute('hidden', locked || !this.started || this.panel !== null); document.body.classList.toggle('playing', locked); };
  }
  start() { this.started = true; document.querySelector('#welcome')!.setAttribute('hidden', ''); document.body.classList.add('started'); this.sound.start(); this.onStart(); void this.player.lock(); if (this.economy.offlineAward > 2) this.toast(`Welcome home. Terra earned ${format(this.economy.offlineAward)} Crowns while you were away.`, 8000); else this.toast('Terra has seen better years. Rook & Son is just beyond the arch.'); }
  toast(message: string, duration = 4500) { const el = document.querySelector('#toast')!; el.textContent = message; el.classList.add('show'); clearTimeout(this.toastTimer); this.toastTimer = window.setTimeout(() => el.classList.remove('show'), duration); }
  openLedger(tab = this.tab) { this.panel = 'ledger'; this.tab = tab; this.selected = null; this.player.release(); document.querySelector('#pause')!.setAttribute('hidden', ''); this.render(); }
  interact(t: Target) { if (t.kind === 'property') { this.economy.inspect(t.id); this.selected = t.id as PropertyId; this.panel = 'property'; this.player.release(); this.render(); } else if (t.kind === 'ledger') this.openLedger(); else if (t.kind === 'district') this.openLedger('Districts'); else { const lore: Record<string, string> = { map: 'The Seven Provinces: Veyr sends iron; Orison sends salt. Terra once kept them all in motion.', automaton: 'A maker’s mark: FINCH, 1841. Its last instruction was “keep the lamps burning.”', shrine: '“No ember is too small.” The first engineers lit this flame when Terra was only a bridge.' }; if (this.economy.discover(t.id)) { this.sound.collect(); this.toast(`${lore[t.id]}  +55 Crowns · +3% income`, 9500); } else this.toast(lore[t.id], 7000); } }
  close(resume = false) { this.panel = null; this.selected = null; this.confirmReset = false; document.querySelector('#panel')!.setAttribute('hidden', ''); if (resume) void this.player.lock(); else document.querySelector('#pause')!.removeAttribute('hidden'); }
  action(action: string, id: string) {
    if (action === 'resume') { this.sound.start(); void this.player.lock(); }
    if (action === 'ledger') this.openLedger(); if (action === 'settings') this.openLedger('Settings'); if (action === 'close') this.close(true); if (action === 'tab') { this.tab = id; this.confirmReset = false; this.render(); }
    if (action === 'track') { this.tracked = id as PropertyId; this.toast(`Follow the marker to ${PROPERTIES.find(p => p.id === id)!.name}.`); this.close(true); }
    if (action === 'collect') { const amount = this.economy.collect(id as PropertyId); if (amount > 0) { this.sound.collect(); this.toast(`Collected ${format(amount)} Crowns. Every small beginning matters.`); this.economy.save(); } this.render(); }
    if (action === 'upgrade') { if (this.economy.upgrade(id as PropertyId)) this.sound.purchase(); else this.toast('The treasury cannot cover that commission yet.'); this.render(); }
    if (action === 'automate') { if (this.economy.automate(id as PropertyId)) { this.sound.purchase(); this.toast('A foreman takes over. All production now reaches the treasury automatically.'); } this.render(); }
    if (action === 'infra') { if (this.economy.upgradeInfra(id as InfraId)) this.sound.purchase(); this.render(); }
    if (action === 'unlock') { if (this.economy.unlock(id)) { this.sound.purchase(); this.toast('Charter approved. The district gates are opening.'); } this.render(); }
    if (action === 'research') { if (this.economy.research(id)) this.sound.purchase(); this.render(); }
    if (action === 'reset-ask') { this.confirmReset = true; this.render(); } if (action === 'reset-cancel') { this.confirmReset = false; this.render(); }
    if (action === 'reset-confirm') { this.economy.reset(); this.onReset(); this.close(false); this.toast('A new stewardship begins.'); }
    if (action === 'quality') { this.economy.state.settings.quality = id as 'low' | 'high'; this.onQuality(); this.economy.save(); this.render(); }
    if (action === 'save') { this.economy.save(); this.toast('City records saved on this device.'); }
  }
  button(action: string, id: string, label: string, cost?: number, extraDisabled = false) { const disabled = extraDisabled || (cost !== undefined && this.economy.state.crowns < cost); return `<button class="purchase" data-action="${action}" data-id="${id}" ${cost === undefined ? '' : `data-cost="${cost}"`} ${extraDisabled ? 'data-locked="true"' : ''} ${disabled ? 'disabled' : ''}><span>${label}</span><b>${cost === undefined ? '↗' : format(cost) + ' ♜'}</b></button>`; }
  render() { if (!this.panel) return; const el = document.querySelector('#panel')!; el.removeAttribute('hidden'); document.querySelector('#pause')!.setAttribute('hidden', '');
    let body = ''; const s = this.economy.state;
    if (this.panel === 'property' && this.selected) { const p = PROPERTIES.find(p => p.id === this.selected)!; const v = s.properties[p.id]; const constructing = this.city.constructions.some(c => Math.abs(c.group.position.x - p.x) < 1 && Math.abs(c.group.position.z - p.z) < 1);
      body = `<div class="overline">${p.kind} / LOWWORKS</div><h2>${p.name}</h2><p class="description">${p.description}</p><div class="level-track">${p.upgrades.map((_, i) => `<span class="${i < v.level ? 'done' : ''}">${String(i + 1).padStart(2, '0')}</span>`).join('')}</div><div class="instrument"><div><small>PRODUCTION</small><strong>${format(this.economy.output(p.id))} <em>♜</em></strong><span>every ${p.interval} seconds</span></div><div><small>CITY CONTRIBUTION</small><strong>${(this.economy.output(p.id) / p.interval * (v.automated ? 1 : .4)).toFixed(1)} <em>/s</em></strong><span>${v.automated ? 'Fully automated' : '40% passive · 60% on site'}</span></div></div><div class="production-bar"><span style="width:${v.progress / p.interval * 100}%"></span></div>`;
      if (!v.automated) body += this.button('collect', p.id, `Collect local earnings`, undefined, v.stored < .1).replace('↗</b>', `${format(v.stored)} ♜</b>`);
      body += `<div class="section-label">NEXT COMMISSION</div>`;
      if (v.level < 5) body += `<h3>${p.upgrades[v.level]}</h3><p class="muted">${v.level === 2 ? 'A major milestone: 50% production bonus and an expanded factory floor.' : v.level === 4 ? 'Masterwork milestone: double output and a luminous aether crown.' : 'Restore the property, raise production, and put Terra’s workers back to work.'} Construction takes 6 seconds.</p>${this.button('upgrade', p.id, constructing ? 'Construction in progress…' : 'Commission improvement', this.economy.cost(p.id), constructing)}`;
      else body += '<h3>Masterwork property</h3><p class="muted">The pride of Terra. All five commissions are complete.</p>';
      body += `<div class="section-label">OPERATIONS</div>${v.automated ? '<p class="status-good">● Foreman on duty · all income deposited automatically</p>' : this.button('automate', p.id, 'Appoint a foreman', p.cost * 2, v.level === 0)}<p class="footnote">${v.level === 0 ? 'Restore this business before appointing a foreman.' : 'Visit to collect reserves, or employ a foreman to handle every delivery.'}</p>`;
    } else {
      body = `<div class="overline">OFFICE OF THE CITY STEWARD</div><h2>The city ledger</h2><nav class="tabs" aria-label="Ledger sections">${['Properties', 'Infrastructure', 'Districts', 'Research', 'Statistics', 'Settings'].map(t => `<button class="${this.tab === t ? 'active' : ''}" data-action="tab" data-id="${t}">${t}</button>`).join('')}</nav>`;
      if (this.tab === 'Properties') { body += `<p class="description">A thousand hands keep Terra turning.<br>Visit a property’s brass ledger to invest.</p>` + PROPERTIES.map(p => `<div class="ledger-row"><div><small>${p.kind} · ${s.properties[p.id].level}/5</small><h3>${p.name}</h3><p>${(this.economy.output(p.id) / p.interval).toFixed(1)} ♜/s potential ${s.properties[p.id].automated ? '· AUTOMATED' : ''}</p></div><button class="find" data-action="track" data-id="${p.id}" aria-label="Find ${p.name}">↗</button></div>`).join(''); }
      if (this.tab === 'Infrastructure') body += `<p class="description">The things a city shares. Every improvement makes the whole district stronger.</p>` + INFRA.map(i => `<div class="ledger-row block"><small>CIVIC WORKS · ${s.infrastructure[i.id]}/3</small><h3>${i.name}</h3><p>${i.detail}</p><p class="status-good">${i.effect}</p>${s.infrastructure[i.id] < 3 ? this.button('infra', i.id, 'Commission level ' + (s.infrastructure[i.id] + 1), this.economy.infraCost(i.id), this.city.constructions.some(c => c.group.position.x === 0)) : '<span class="complete">FULLY RESTORED</span>'}</div>`).join('');
      if (this.tab === 'Districts') body += `<div class="map"><svg viewBox="0 0 400 240" role="img" aria-label="Map: Lowworks in the center, Canal Ward east, Aether Heights north"><path d="M200 215V40M115 80H290M115 140H315M315 35v180" fill="none" stroke="#8f835d" stroke-width="3"/><path d="M282 0v240" stroke="#497773" stroke-width="12"/><g fill="#345150" stroke="#8f835d"><rect x="135" y="95" width="40" height="30"/><rect x="220" y="95" width="40" height="30"/><rect x="135" y="155" width="40" height="35"/><rect x="220" y="155" width="40" height="35"/><circle cx="200" cy="57" r="10"/></g><g fill="#ddcc9f" font-size="10" font-family="Georgia" text-anchor="middle"><text x="200" y="232">ARRIVAL</text><text x="200" y="18">AETHER HEIGHTS</text><text x="200" y="87">LOWWORKS</text><text x="344" y="129">CANAL</text><text x="344" y="143">WARD</text></g><circle cx="${200 + this.player.position.x * 1.5}" cy="${105 + this.player.position.z * 1.5}" r="4" fill="#f6d897"/></svg></div>` + [{ id: 'canal', name: 'The Canal Ward', desc: 'Cross the restored bridge into the trading quarter. +25% city income.', cost: 750, stage: 1 }, { id: 'heights', name: 'Aether Heights', desc: 'Beyond the clock tower, the institute waits for a new age. +25% city income.', cost: 3000, stage: 3 }].map(d => `<div class="ledger-row block"><small>EXPANSION CHARTER</small><h3>${d.name}</h3><p>${d.desc}</p>${s.districts.includes(d.id) ? '<span class="complete">GATES OPEN</span>' : this.button('unlock', d.id, this.economy.stage < d.stage ? `Requires ${STAGES[d.stage]}` : 'Approve the charter', d.cost, this.economy.stage < d.stage)}</div>`).join('');
      if (this.tab === 'Research') body += `<p class="description">The Finch Institute’s applied sciences.<br>Each discovery raises city output by 25%.</p>` + [{ id: 'governors', name: 'Precision governors', cost: 450, stage: 1, desc: 'A steady engine wastes less work. Synchronize Terra’s industrial machinery.' }, { id: 'aether', name: 'Aether induction', cost: 1800, stage: 3, desc: 'The light in the old shrine can be harnessed. Copper and crystal, working together.' }, { id: 'charter', name: 'The Seven Provinces charter', cost: 4500, stage: 3, desc: 'Unite Locke’s merchants under the seal of Terra.' }].map(r => `<div class="ledger-row block"><small>APPLIED SCIENCE</small><h3>${r.name}</h3><p>${r.desc}</p>${s.research.includes(r.id) ? '<span class="complete">RESEARCH COMPLETE</span>' : this.button('research', r.id, this.economy.stage < r.stage ? `Requires ${STAGES[r.stage]}` : 'Fund the research', r.cost, this.economy.stage < r.stage)}</div>`).join('');
      if (this.tab === 'Statistics') body += `<div class="city-stage"><span>PROSPERITY ${this.economy.stage} / 5</span><h3>${STAGES[this.economy.stage]}</h3><p>${this.economy.investment} civic & business commissions</p></div>` + [['Treasury', `${format(s.crowns)} Crowns`], ['Lifetime earnings', `${format(s.earned)} Crowns`], ['Passive income', `${this.economy.rate.toFixed(2)} / second`], ['City production multiplier', `${this.economy.multiplier.toFixed(2)}×`], ['Stewardship time', `${Math.floor(s.playtime / 60)} minutes`], ['District charters', `${s.districts.length} / 2`], ['Discoveries', `${s.discoveries.length} / 3`], ['Offline dividends', 'Up to 4 hours']].map(([a, b]) => `<div class="stat-row"><span>${a}</span><b>${b}</b></div>`).join('') + '<p class="footnote">Unstaffed properties pay 40% directly and reserve 60% for on-site collection. Foremen automate the full output. Offline income includes automatic dividends only.</p>';
      if (this.tab === 'Settings') { body += '<p class="description">Make yourself at home in Terra.</p>'; for (const [key, label] of [['master', 'Master volume'], ['ambience', 'City ambience'], ['sfx', 'Effects & footsteps'], ['sensitivity', 'Mouse sensitivity']] as const) body += `<label class="slider"><span>${label}</span><input type="range" min="${key === 'sensitivity' ? '.2' : '0'}" max="${key === 'sensitivity' ? '2' : '1'}" step=".05" value="${s.settings[key]}" data-setting="${key}"/></label>`;
        body += `<p class="footnote">Original synthesized city soundscape. No music track is used.</p><label class="check"><input type="checkbox" data-setting="reducedMotion" ${s.settings.reducedMotion ? 'checked' : ''}/> Reduced motion · disable camera bob</label><div class="section-label">RENDER QUALITY</div><div class="quality">${['high', 'low'].map(q => `<button data-action="quality" data-id="${q}" class="${s.settings.quality === q ? 'active' : ''}">${q === 'high' ? 'Full atmosphere' : 'Performance'}</button>`).join('')}</div><div class="section-label">CITY RECORDS</div>${this.button('save', '', 'Save now')}<p class="footnote">Autosaved every 10 seconds and when you invest. Stored locally in this browser.</p>${this.confirmReset ? `<div class="danger"><h3>Start a new stewardship?</h3><p>This permanently clears this browser’s city, treasury, and discoveries.</p><button data-action="reset-confirm">Reset save & start new game</button><button data-action="reset-cancel">Keep my city</button></div>` : '<button class="plain danger-text" data-action="reset-ask">New game / reset save</button>'}`;
      }
    }
    el.innerHTML = `<div class="panel-top"><span>${crest} TERRA · MUNICIPAL RECORDS</span><button data-action="close" aria-label="Close ledger">×</button></div><div class="panel-scroll">${body}</div><div class="panel-bottom"><span>♜ <b id="panel-crowns">${format(s.crowns)}</b> CROWNS AVAILABLE</span><small>ESC TO CLOSE</small></div>`;
  }
  update(weather: string, fps: number, debug: boolean) { const e = this.economy; document.querySelector('#crowns')!.textContent = format(e.state.crowns); document.querySelector('#rate')!.textContent = '+' + e.rate.toFixed(1); document.querySelector('#stage')!.textContent = `${String(e.stage).padStart(2, '0')} / ${STAGES[e.stage].toUpperCase()}`;
    const objectives = ['Inspect the old Scrap Yard.', 'Collect the Scrap Yard’s first earnings.', 'Repair the sorting rig.', 'Restore the district boiler.', 'Bring light back to the streets.', `Build toward ${STAGES[Math.min(5, e.stage + 1)]}. Every commission changes Terra.`]; document.querySelector('#objective')!.textContent = objectives[e.state.objective]; const day = e.state.day; const hour = Math.floor(day * 24); document.querySelector('#weather')!.textContent = `${weather === 'rain' ? 'DRIZZLE' : weather === 'fog' ? 'INDUSTRIAL FOG' : 'OVERCAST'} · ${hour >= 6 && hour < 10 ? 'DAWN' : hour >= 10 && hour < 17 ? 'DAY' : hour >= 17 && hour < 21 ? 'DUSK' : 'NIGHT'}`;
    const angle = ((-this.player.yaw * 180 / Math.PI) % 360 + 360) % 360; document.querySelector('#compass')!.textContent = ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'][Math.round(angle / 45) % 8]; const target = this.player.target; const prompt = document.querySelector('#interaction')!; prompt.toggleAttribute('hidden', !target || !this.player.locked); if (target) prompt.innerHTML = `<kbd>E</kbd><span>${target.label}<small>${target.kind === 'property' ? 'OPEN PROPERTY LEDGER' : target.kind === 'discovery' ? 'EXAMINE DISCOVERY' : 'INTERACT'}</small></span>`;
    const tracked = document.querySelector('#tracked')!; tracked.toggleAttribute('hidden', !this.tracked || !this.player.locked || !!target); if (this.tracked && this.player.locked) { const p = PROPERTIES.find(p => p.id === this.tracked)!; const dx = p.x - this.player.position.x; const dz = p.z - this.player.position.z; const distance = Math.hypot(dx, dz); const relative = Math.atan2(-dx, -dz) - this.player.yaw; tracked.innerHTML = `<span style="display:inline-block;transform:rotate(${-relative}rad)">↑</span> ${p.name} <small>${Math.floor(distance)} m</small>`; }
    document.querySelectorAll<HTMLButtonElement>('.purchase[data-cost]').forEach(b => { b.disabled = b.dataset.locked === 'true' || e.state.crowns < Number(b.dataset.cost); }); if (this.selected) { const p = e.state.properties[this.selected]; const collect = document.querySelector<HTMLButtonElement>('[data-action=collect]'); if (collect) { collect.disabled = p.stored < .1; collect.querySelector('b')!.textContent = format(p.stored) + ' ♜'; } const bar = document.querySelector<HTMLElement>('.production-bar span'); if (bar) bar.style.width = p.progress / PROPERTIES.find(v=>v.id === this.selected)!.interval * 100 + '%'; } const pc = document.querySelector('#panel-crowns'); if (pc) pc.textContent = format(e.state.crowns); const db = document.querySelector('#debug')!; db.toggleAttribute('hidden', !debug); if (debug) db.textContent = `${Math.round(fps)} FPS · ${this.player.position.x.toFixed(1)}, ${this.player.position.y.toFixed(1)}, ${this.player.position.z.toFixed(1)} · Tier ${e.stage}`;
  }
}
