import { clock, curfewNotice, districtAt, district, heatName } from '../simulation/occupation';
import { Economy, PROPERTIES, INFRA, STAGES, TRAITS, OFFLINE, ANCHOR_CLUES, ANCHOR_CASE, format, type PropertyId, type InfraId, type SiteId } from '../simulation/economy';
import { Consignment } from '../world/logistics';
import type { Player } from '../player/controller';
import type { City, Target } from '../world/city';
import type { Soundscape } from '../audio/sound';
const crest = `<svg viewBox="0 0 40 48" aria-hidden="true"><path d="M4 3h32v26L20 44 4 29z"/><path d="M11 13h18m-9 0v20M13 19h14"/></svg>`;
/** What the Steward notices. Short, and never an explanation. */
const LORE: Record<string, string> = { map: 'The Seven Provinces: Veyr sends iron; Orison sends salt. Terra once kept them all in motion.', automaton: 'A maker’s mark: FINCH, 1841. Its last instruction was “keep the lamps burning.”', shrine: '“No ember is too small.” The first engineers lit this flame when Terra was only a bridge.',
      archive: 'Record cylinders, shelved by a hand older than the brick around them. One label is still legible: “Lift ledger — all seven anchors holding.”', weathervane: 'A lens ringed in gold, sighted on the eastern isle. The Ordinance bricked up the door below and never found the way up.',
      hearth: 'Candle stubs and a row of names scratched small. The last one is fresh. Someone still comes here.', undergate: 'Ivory, fitted without a seam, and warm to the touch. Whatever is behind it is still running.',
      registry: 'Every household in the ward, with a column for PERMITTED and a column for WATCHED. One drawer has been left open, tied with a turquoise ribbon. Somebody inside is on your side.', packetlight: 'The signal book is still on its hook. The last entry: “Orison packet, on time. Lamp trimmed. Ordinance vessel, unannounced.” Nothing after it.', pigeons: 'Each bird wears a brass tag stamped with a ward number. Finch’s ledger of flights goes back further than the Ordinance does.', anchor: 'The clasp is older than the iron around it. III is stamped beneath a seven-point seal. It is holding.',
  survey: 'An Ordinance survey sheet. Seven marks along Terra’s keel, each labelled FOUNDATION STABILISER. Three are ringed. Stamped across the corner, twice: DO NOT LOAD.',
  studs: 'Through the glass: seven studs set round the Weathervane’s cap. Six are dull gold. The third is turquoise.',
  gate: 'Under the chains, cut into the lintel: ANCHOR V. Below it, smaller: TEND FROM BELOW.',
  collar: 'A casting pattern for a collar with seven lugs. The order slip reads REPLACEMENT, TO THE OLD GAUGE. Three castings lie cracked beside it.',
  sightline: 'Two brass sighting rings bolted to the rail. One holds the Weathervane’s cap. The other is tilted down, at nothing: cloud, below Terra’s rim.',
  chart: 'Seven lenses in a ring. The third burns steady. The fifth is faint. The rest are dark.',
  backwater: 'A length of ivory conduit, sawn through and used as a gutter. The cut end is warm.' };
export class Interface {
  app = document.querySelector<HTMLDivElement>('#app')!; started = false; panel: string | null = null; tab = 'Properties'; selected: PropertyId | null = null; tracked: PropertyId | null = 'scrap'; siteKey = ''; confirmReset = false; toastTimer = 0;
  onStart: () => void = () => {}; onReset: () => void = () => {}; onQuality: () => void = () => {};
  constructor(public economy: Economy, public player: Player, public city: City, public sound: Soundscape) { this.app.innerHTML = `
    <div class="vignette"></div><header id="hud"><div class="identity">${crest}<div><b>CITY TYCOON</b><span>TERRA <i> / </i> LOCKE</span></div></div><div class="bearing"><span id="compass">N</span><small id="weather">DRIZZLE · DUSK</small><small id="ward" class="ward">THE LOWWORKS · 80% · HEAVY OCCUPATION</small></div><div class="hour" aria-live="off"><span id="clock">17:16</span><small id="curfew"></small></div><div class="treasury"><span class="coin">♜</span><div><small>CITY TREASURY</small><strong id="crowns">35</strong></div><div class="income"><b id="rate">+0</b><small>CROWNS / SEC</small></div></div></header>
    <div id="crosshair"></div><div id="interaction" hidden></div><div id="tracked" hidden></div><div id="toast" role="status"></div>
    <footer id="hud-bottom"><div class="objective"><span class="overline">A CITY WORTH SAVING</span><p id="objective">Inspect the old Scrap Yard.</p><small id="stage">00 / THE LOWWORKS</small></div><div class="controls"><span><kbd>W A S D</kbd> Walk</span><span><kbd>E</kbd> Interact</span><span><kbd>⇧</kbd> Sprint</span><button class="ledger-control" data-action="ledger"><kbd>TAB</kbd> City ledger</button></div></footer>
    <section id="welcome" class="welcome"><div class="eyebrow"><span></span> WORLD OF LOCKE · CHAPTER I</div><div class="title-stamp">A STEAMPUNK CITY TALE</div><h1 aria-label="Terra"><span>TER</span><span>RA<span class="title-dot">.</span></span></h1><p>A little soot. A little steam.<br>A whole city to bring back to life.</p><button id="enter" class="primary">${economy.state.playtime > 1 ? 'Continue stewardship' : 'Enter the Lowworks'} <span>↗</span></button><div class="welcome-foot">EXPLORE · RESTORE · WATCH IT GROW</div></section>
    <section id="pause" class="pause" hidden><div class="eyebrow">THE CITY KEEPS TURNING</div><h2>Take a breath.</h2><p>Your businesses continue working while you’re here.</p><button data-action="resume" class="primary">Return to Terra <span>↗</span></button><button data-action="ledger" class="plain">Open city ledger</button><button data-action="settings" class="plain">Settings</button></section>
    <aside id="panel" class="panel" hidden aria-label="City ledger"></aside><div id="debug" hidden></div><div id="save-status" role="status"></div>`;
    document.body.classList.toggle('reduced-motion', economy.state.settings.reducedMotion);
    document.querySelector('#enter')!.addEventListener('click', () => this.start());
    this.app.addEventListener('click', e => { const button = (e.target as HTMLElement).closest<HTMLElement>('[data-action]'); if (button && !button.hasAttribute('disabled')) this.action(button.dataset.action!, button.dataset.id ?? ''); });
    this.app.addEventListener('input', e => { const input = e.target as HTMLInputElement; const key = input.dataset.setting; if (!key) return; const s = this.economy.state.settings; if (key === 'reducedMotion') s.reducedMotion = input.checked; else if (['master', 'ambience', 'sfx', 'music', 'sensitivity'].includes(key)) (s as unknown as Record<string, number>)[key] = Number(input.value); document.body.classList.toggle('reduced-motion', s.reducedMotion); this.sound.apply(); this.economy.save(); });
    document.addEventListener('keydown', e => { if (!this.started || e.repeat) return; if (e.code === 'Tab' && !this.panel && this.player.locked) { e.preventDefault(); this.openLedger(); } if (e.code === 'Escape' && this.panel) this.close(false); });
    player.onInteract = t => this.interact(t); player.onLock = locked => { document.querySelector('#pause')!.toggleAttribute('hidden', locked || !this.started || this.panel !== null); document.body.classList.toggle('playing', locked); };
  }
  start() { this.started = true; document.querySelector('#welcome')!.setAttribute('hidden', ''); document.body.classList.add('started'); this.sound.start(); this.onStart(); void this.player.lock(); if (this.economy.offlineAward > 2) this.toast(`Welcome home. Terra earned ${format(this.economy.offlineAward)} Crowns while you were away.`, 8000); else this.toast('Terra has seen better years. Rook & Son is just beyond the arch.'); }
  /** The clock and the ward the Steward is standing in: both read the one game clock and the one occupation rule. */
  private ward = ''; private band = '';
  wardLine() { const e = this.economy, p = this.player.position, id = districtAt(p.x, p.z), pct = e.occupationOf(id), band = e.effects(id), notice = curfewNotice(e.state.day, e.band(id));
    document.querySelector('#clock')!.textContent = clock(e.state.day).text; const c = document.querySelector('#curfew')!; c.textContent = notice || (e.state.heat >= .5 ? heatName(e.state.heat).toUpperCase() : ''); c.classList.toggle('on', notice === 'CURFEW');
    const w = document.querySelector('#ward')!; w.textContent = `${district(id).name} · ${pct}% · ${band.name}`.toUpperCase(); w.setAttribute('data-band', e.band(id));
    // Walking into a ward, or a ward changing under your feet, says what that means once. The street says the rest.
    if (this.started && (id !== this.ward || band.name !== this.band)) { const first = !this.ward; this.ward = id; this.band = band.name; if (!first) this.toast(`${district(id).name} · Occupation ${pct}% · ${band.name}. ${band.notes.join(' · ')}.`, 5200); } }
  toast(message: string, duration = 4500) { const el = document.querySelector('#toast')!; el.textContent = message; el.classList.add('show'); clearTimeout(this.toastTimer); this.toastTimer = window.setTimeout(() => el.classList.remove('show'), duration); }
  openLedger(tab = this.tab) { this.panel = 'ledger'; this.tab = tab; this.selected = null; this.player.release(); document.querySelector('#pause')!.setAttribute('hidden', ''); this.render(); document.querySelector<HTMLButtonElement>('#panel [data-action=close]')?.focus(); }
  /** Home: a night's sleep passes the time to morning, pays what the trades pay unattended, and lets the patrols forget a little. */
  rest() { const r = this.economy.sleep(); if (!r) return this.toast('Too early to sleep. The room is yours all the same: nobody watches a Steward at home.', 6000);
    this.sound.collect(); this.toast(`You sleep ${r.hours} hours. Six in the morning; the curfew is lifted.${r.award >= 1 ? ` The trades brought in ${format(r.award)} Crowns overnight.` : ''}`, 9000); }
  answer() { const got = this.economy.signal(); if (!got) return; this.sound.purchase(); this.toast(`You turn the lamp up, twice. The Weathervane answers, and something crosses the roofs toward the cellar. +${format(got)} Crowns by morning.`, 9500); }
  interact(t: Target) { if (t.kind === 'home') return this.rest(); if (t.kind === 'signal') return this.answer(); if (t.kind === 'property') { this.economy.inspect(t.id); this.selected = t.id as PropertyId; this.panel = 'property'; this.player.release(); this.render(); } else if (t.kind === 'lift') this.city.edge.startRide(this.player, t.id === 'lift.down'); else if (t.kind === 'ladder') { const l = this.city.ladders.find(l => l.id === t.id); if (l) this.player.climb(l); } else if (t.kind === 'ledger') this.openLedger(); else if (t.kind === 'district') this.openLedger('Districts'); else if (t.kind === 'site') { const load = Consignment.all.find(c => c.id === t.id), held = Consignment.carried(); if (load) this.carry(load); else if (held?.deliverAt === t.id) this.deliver(held); else this.openSite(t.id); } else { const text = LORE[t.id] ?? '';
      if (this.economy.discover(t.id)) { this.sound.collect(); this.toast(`${text}  +55 Crowns · +3% income`, 9500); return; }
      // An observation is kept, not collected. If it changes what can be done, say so in one line.
      const before = this.economy.researchBlocker('anchors'), price = this.economy.charterCost('anchors'), fresh = this.economy.learn(t.id);
      if (!fresh) { this.toast(text, 7000); return; }
      this.sound.collect(); const after = this.economy.researchBlocker('anchors');
      const clue = (ANCHOR_CLUES as readonly string[]).includes(t.id), e = this.economy, wasCase = clue && before !== null && /rumour|Not yet/.test(before), isCase = e.state.knowledge.includes('anchor') && e.anchorClues >= ANCHOR_CASE; void after;
      const consequence = !clue ? '' : wasCase && isCase ? ' That is a case. The Finch Institute will hear it.' : t.id === 'survey' && e.charterCost('anchors') < price ? ' The Institute can work from their measurements.' : !isCase && e.state.knowledge.includes('anchor') ? ' The Institute will want more than this.' : '';
      this.toast(text + consequence, 9500); if (this.panel) this.render(); } }
  /** Logistics in the Steward's own arms: take the Foundry's cutters crate, and hand it over at the Finch cellar. */
  carry(load: Consignment) { this.toast(load.take() ?? load.taken, 8000); }
  /** Delivery happens where the goods are received; it is covert, so watching eyes there refuse it. */
  deliver(load: Consignment) { const at = load.deliverAt.split('.')[0] as SiteId; if (this.city.watched(at)) return this.toast(this.economy.site(at).watched); if (this.economy.deliver(load.site)) { load.drop(); this.sound.purchase(); } }
  /** Physical places, not menus: each site's spots (a cellar door, a shift board, a spring,
   * a forge) carry their own steps. Covert spots refuse while occupation eyes are on you. */
  openSite(key: string) { const [id, name] = key.split('.') as [SiteId, string]; const s = this.economy.state, level = s.sites[id], site = this.economy.site(id), spot = site.spots[name];
    if (level < spot.from) return this.toast(spot.before, 8000);
    if (level > spot.to) return this.toast(spot.after, 7000);
    const closed = spot.closed?.(s); if (closed) return this.toast(closed);
    if (spot.covert && this.city.watched(id)) return this.toast(site.watched);
    this.siteKey = key; this.panel = 'site'; this.player.release(); this.render(); }
  close(resume = false) { this.panel = null; this.selected = null; this.confirmReset = false; document.querySelector('#panel')!.setAttribute('hidden', ''); if (resume) void this.player.lock(); else document.querySelector('#pause')!.removeAttribute('hidden'); }
  action(action: string, id: string) {
    if (action === 'resume') { this.sound.start(); void this.player.lock(); }
    if (action === 'ledger') this.openLedger(); if (action === 'settings') this.openLedger('Settings'); if (action === 'close') this.close(true); if (action === 'tab') { this.tab = id; this.confirmReset = false; this.render(); document.querySelector<HTMLButtonElement>(`#panel [data-action=tab][data-id="${id}"]`)?.focus(); }
    if (action === 'track') { this.tracked = id as PropertyId; this.toast(`Follow the marker to ${PROPERTIES.find(p => p.id === id)!.name}.`); this.close(true); }
    if (action === 'collect') { const amount = this.economy.collect(id as PropertyId); if (amount > 0) { this.sound.collect(); this.toast(`Collected ${format(amount)} Crowns. Every small beginning matters.`); this.economy.save(); } this.render(); }
    if (action === 'upgrade') { if (this.economy.upgrade(id as PropertyId)) this.sound.purchase(); else this.toast('The treasury cannot cover that commission yet.'); this.render(); }
    if (action === 'automate') { if (this.economy.automate(id as PropertyId)) { this.sound.purchase(); this.toast('A foreman takes over. All production now reaches the treasury automatically.'); } this.render(); }
    if (action === 'site') { if (this.economy.advanceSite(id as SiteId)) { this.sound.purchase(); this.close(true); } else this.toast('The treasury cannot cover that yet.'); return; }
    if (action === 'infra') { if (this.economy.upgradeInfra(id as InfraId)) this.sound.purchase(); this.render(); }
    if (action === 'unlock') { if (this.economy.unlock(id)) { this.sound.purchase(); this.toast('Charter approved. The district gates are opening.'); } this.render(); }
    if (action === 'research') { if (this.economy.research(id)) this.sound.purchase(); this.render(); }
    if (action === 'reset-ask') { this.confirmReset = true; this.render(); } if (action === 'reset-cancel') { this.confirmReset = false; this.render(); }
    if (action === 'reset-confirm') { this.economy.reset(); this.onReset(); this.close(false); this.toast('A new stewardship begins.'); }
    if (action === 'quality') { this.economy.state.settings.quality = id as 'low' | 'high'; this.onQuality(); this.economy.save(); this.render(); }
    if (action === 'save') { this.economy.save(); this.toast('City records saved on this device.'); }
  }
  button(action: string, id: string, label: string, cost?: number, extraDisabled = false) { const disabled = extraDisabled || (cost !== undefined && this.economy.state.crowns < cost); const saved = cost ? Math.min(100, Math.floor(this.economy.state.crowns / cost * 100)) : 100; return `<button class="purchase" style="--saved:${saved}%" data-action="${action}" data-id="${id}" ${cost === undefined ? '' : `data-cost="${cost}"`} ${extraDisabled ? 'data-locked="true"' : ''} ${disabled ? 'disabled' : ''}><span>${label}</span><b>${cost === undefined ? '↗' : format(cost) + ' ♜'}</b></button>`; }
  render() { if (!this.panel) return; const el = document.querySelector('#panel')!; el.removeAttribute('hidden'); document.querySelector('#pause')!.setAttribute('hidden', '');
    let body = ''; const s = this.economy.state;
    if (this.panel === 'site') { const id = this.siteKey.split('.')[0] as SiteId, site = this.economy.site(id), level = s.sites[id], step = site.steps[level], blocker = this.economy.siteBlocker(id), busy = this.city.constructions.some(c => c.site === id);
      const voice = site.voice[step.kind];
      body = `<div class="overline">${voice[0]}</div><h2>${site.name}</h2><p class="description">${voice[1]}</p><div class="level-track">${site.steps.map((_, i) => `<span class="${i < level ? 'done' : ''}">${String(i + 1).padStart(2, '0')}</span>`).join('')}</div><div class="section-label">${step.kind === 'covert' ? 'QUIET WORK' : step.kind === 'liberation' ? 'OPEN RESISTANCE' : 'RESTORATION'}</div><h3>${step.name}</h3><p class="muted">${step.detail}${step.kind === 'liberation' ? ' Lifting the occupation levy raises city income by 15%.' : step.kind === 'restoration' ? ' The running spring adds another 10% to city income.' : ''}</p>${this.button('site', id, busy ? 'Work in progress…' : blocker ?? voice[2], this.economy.siteCost(id), !!blocker || busy)}`;
    } else if (this.panel === 'property' && this.selected) { const p = PROPERTIES.find(p => p.id === this.selected)!; const v = s.properties[p.id]; const constructing = this.city.constructions.some(c => Math.abs(c.group.position.x - p.x) < 1 && Math.abs(c.group.position.z - p.z) < 1);
      body = `<div class="overline">${p.kind} / LOWWORKS</div><h2>${p.name}</h2><p class="description">${p.description}</p><div class="level-track">${p.upgrades.map((_, i) => `<span class="${i < v.level ? 'done' : ''}">${String(i + 1).padStart(2, '0')}</span>`).join('')}</div><div class="instrument"><div><small>PRODUCTION</small><strong>${format(this.economy.output(p.id))} <em>♜</em></strong><span>every ${p.interval} seconds</span></div><div><small>CITY CONTRIBUTION</small><strong>${(this.economy.output(p.id) / p.interval * (v.automated ? 1 : .4)).toFixed(1)} <em>/s</em></strong><span>${v.automated ? 'Fully automated' : '40% passive · 60% on site'}</span></div></div><div class="production-bar"><span style="width:${v.progress / p.interval * 100}%"></span></div>`;
      // What this trade does for everything else: the reason to raise it ahead of its neighbours.
      { const t = TRAITS[p.id], pct = (n: number) => Math.round(t.per * n * 100); const worth = this.economy.traitWorth(p.id); body += `<p class="footnote"><b>${t.name.toUpperCase()}</b> · ${v.level ? `${pct(v.level)}% ${t.effect}` : `nothing yet`}${worth.now ? ` (${format(worth.now)} ♜ on the work still to do)` : ''}${v.level < 5 ? ` · next level: ${pct(v.level + 1)}%${worth.next ? `, worth about ${format(worth.next)} ♜ more` : ''}` : ''}</p>`; }
      if (!v.automated) body += this.button('collect', p.id, `Collect local earnings`, undefined, v.stored < .1).replace('↗</b>', `${format(v.stored)} ♜</b>`);
      body += `<div class="section-label">NEXT COMMISSION</div>`;
      if (v.level < 5) body += `<h3>${p.upgrades[v.level]}</h3><p class="muted">${v.level === 2 ? 'A major milestone: 50% production bonus and an expanded factory floor.' : v.level === 4 ? 'Masterwork milestone: double output and a luminous aether crown.' : 'Restore the property, raise production, and put Terra’s workers back to work.'} Construction takes ${this.economy.buildSeconds(v.level + 1)} seconds.</p>${this.button('upgrade', p.id, constructing ? 'Construction in progress…' : 'Commission improvement', this.economy.cost(p.id), constructing)}`;
      else body += '<h3>Masterwork property</h3><p class="muted">The pride of Terra. All five commissions are complete.</p>';
      body += `<div class="section-label">OPERATIONS</div>${v.automated ? '<p class="status-good">● Foreman on duty · all income deposited automatically</p>' : this.button('automate', p.id, 'Appoint a foreman', this.economy.foremanCost(p.id), v.level === 0)}<p class="footnote">${v.level === 0 ? 'Restore this business before appointing a foreman.' : 'Visit to collect reserves, or employ a foreman to handle every delivery.'}</p>`;
    } else {
      body = `<div class="overline">OFFICE OF THE CITY STEWARD</div><h2>The city ledger</h2><nav class="tabs" aria-label="Ledger sections">${['Properties', 'Infrastructure', 'Districts', 'Research', 'Statistics', 'Settings'].map(t => `<button class="${this.tab === t ? 'active' : ''}" data-action="tab" data-id="${t}">${t}</button>`).join('')}</nav>`;
      if (this.tab === 'Properties') { body += `<p class="description">A thousand hands keep Terra turning.<br>Visit a property’s brass ledger to invest.</p>` + PROPERTIES.map(p => `<div class="ledger-row"><div><small>${p.kind} · ${s.properties[p.id].level}/5</small><h3>${p.name}</h3><p>${(this.economy.output(p.id) / p.interval).toFixed(1)} ♜/s potential ${s.properties[p.id].automated ? '· AUTOMATED' : ''}</p></div><button class="find" data-action="track" data-id="${p.id}" aria-label="Find ${p.name}">↗</button></div>`).join(''); }
      if (this.tab === 'Infrastructure') body += `<p class="description">The things a city shares. Every improvement makes the whole district stronger.</p>` + INFRA.map(i => `<div class="ledger-row block"><small>CIVIC WORKS · ${s.infrastructure[i.id]}/3</small><h3>${i.name}</h3><p>${i.detail}</p><p class="status-good">${i.effect}</p>${s.infrastructure[i.id] < 3 ? this.button('infra', i.id, 'Commission level ' + (s.infrastructure[i.id] + 1), this.economy.infraCost(i.id), this.city.constructions.some(c => c.group.position.x === 0)) : '<span class="complete">FULLY RESTORED</span>'}</div>`).join('');
      if (this.tab === 'Districts') body += `<div class="map"><svg viewBox="0 0 400 240" role="img" aria-label="Map: Lowworks in the center, Canal Ward east, Aether Heights north"><path d="M200 215V40M115 80H290M115 140H315M315 35v180" fill="none" stroke="#8f835d" stroke-width="3"/><path d="M282 0v240" stroke="#497773" stroke-width="12"/><g fill="#345150" stroke="#8f835d"><rect x="135" y="95" width="40" height="30"/><rect x="220" y="95" width="40" height="30"/><rect x="135" y="155" width="40" height="35"/><rect x="220" y="155" width="40" height="35"/><circle cx="200" cy="57" r="10"/></g><g fill="#ddcc9f" font-size="10" font-family="Georgia" text-anchor="middle"><text x="200" y="232">ARRIVAL</text><text x="200" y="18">AETHER HEIGHTS</text><text x="200" y="87">LOWWORKS</text><text x="344" y="129">CANAL</text><text x="344" y="143">WARD</text></g><circle cx="${200 + this.player.position.x * 1.5}" cy="${105 + this.player.position.z * 1.5}" r="4" fill="#f6d897"/></svg></div>` + [{ id: 'canal', name: 'The Canal Ward', desc: 'Cross the restored bridge into the trading quarter. +25% city income.', cost: this.economy.charterCost('canal'), stage: 1 }, { id: 'heights', name: 'Aether Heights', desc: 'Beyond the clock tower, the institute waits for a new age. +25% city income.', cost: this.economy.charterCost('heights'), stage: 3 }].map(d => `<div class="ledger-row block"><small>EXPANSION CHARTER</small><h3>${d.name}</h3><p>${d.desc}</p>${s.districts.includes(d.id) ? '<span class="complete">GATES OPEN</span>' : this.button('unlock', d.id, this.economy.stage < d.stage ? `Requires ${STAGES[d.stage]}` : 'Approve the charter', d.cost, this.economy.stage < d.stage)}</div>`).join('');
      if (this.tab === 'Research') { const e = this.economy, list = [
        { id: 'governors', name: 'Precision governors', desc: 'A steady engine wastes less work. Flyball governors on the Great Main, and the civic engineers build in half the time.' },
        { id: 'aether', name: 'Aether induction', desc: 'The light in the old shrine can be harnessed. The old works take it back: the garden fountain, the cistern, the sealed gate, and the Weathervane answers the eastern isle.' },
        { id: 'charter', name: 'The Seven Provinces charter', desc: 'Unite Locke’s merchants under the seal of Terra. Their colours fly over the main street and their traders set up in the square.' },
        // Not offered on prosperity alone: it appears once the Steward has seen something to ask about.
        ...(e.anchorClues > 0 || s.research.includes('anchors') ? [{ id: 'anchors', name: 'The Anchor survey', desc: s.knowledge.includes('survey') ? 'Something is clasped round the ribs under Terra. The Ordinance has already measured it; the Institute can start from their figures.' : 'Something is clasped round the ribs under Terra. Measure it properly, and find out what it is holding.' }] : [])];
        body += `<p class="description">The Finch Institute’s applied sciences.<br>Each raises city output by 25%, and each changes something you can go and see.</p>` + list.map(r => { const blocker = e.researchBlocker(r.id); return `<div class="ledger-row block"><small>${r.id === 'anchors' ? `FIELD SURVEY · ${Math.min(e.anchorClues, ANCHOR_CASE)} OF ${ANCHOR_CASE} OBSERVATIONS` : 'APPLIED SCIENCE'}</small><h3>${r.name}</h3><p>${r.desc}</p>${s.research.includes(r.id) ? '<span class="complete">RESEARCH COMPLETE</span>' : this.button('research', r.id, blocker ?? (r.id === 'anchors' ? 'Fund the survey' : 'Fund the research'), e.charterCost(r.id), !!blocker)}</div>`; }).join(''); }
      if (this.tab === 'Statistics') body += `<div class="city-stage"><span>PROSPERITY ${this.economy.stage} / 5</span><h3>${STAGES[this.economy.stage]}</h3><p>${this.economy.investment} civic & business commissions</p></div>` + [['Treasury', `${format(s.crowns)} Crowns`], ['Lifetime earnings', `${format(s.earned)} Crowns`], ['Passive income', `${this.economy.rate.toFixed(2)} / second`], ['City production multiplier', `${this.economy.multiplier.toFixed(2)}×`], ['Stewardship time', `${Math.floor(s.playtime / 60)} minutes`], ['District charters', `${s.districts.length} / 2`], ['Discoveries', `${s.discoveries.length} / 3`], ['Dividends while away', `${Math.round(this.economy.awayShare * 100)}% · up to ${OFFLINE.hours} hours`]].map(([a, b]) => `<div class="stat-row"><span>${a}</span><b>${b}</b></div>`).join('') + '<p class="footnote">Unstaffed properties pay 40% directly and reserve 60% for on-site collection. Foremen automate the full output. Offline income includes automatic dividends only.</p>';
      if (this.tab === 'Settings') { body += '<p class="description">Make yourself at home in Terra.</p>'; for (const [key, label] of [['master', 'Master volume'], ['ambience', 'City ambience'], ['sfx', 'Effects & footsteps'], ['sensitivity', 'Mouse sensitivity']] as const) body += `<label class="slider"><span>${label}</span><input type="range" min="${key === 'sensitivity' ? '.2' : '0'}" max="${key === 'sensitivity' ? '2' : '1'}" step=".05" value="${s.settings[key]}" data-setting="${key}"/></label>`;
        body += `<p class="footnote">Original synthesized city soundscape. No music track is used.</p><label class="check"><input type="checkbox" data-setting="reducedMotion" ${s.settings.reducedMotion ? 'checked' : ''}/> Reduced motion · calm camera & transitions</label><p class="footnote">Your device’s reduced-motion preference is also respected.</p><div class="section-label">RENDER QUALITY</div><div class="quality">${['high', 'low'].map(q => `<button data-action="quality" data-id="${q}" class="${s.settings.quality === q ? 'active' : ''}">${q === 'high' ? 'Full atmosphere' : 'Performance'}</button>`).join('')}</div><div class="section-label">CITY RECORDS</div>${this.button('save', '', 'Save now')}<p class="footnote">Autosaved every 10 seconds and when you invest. Stored locally in this browser.</p>${this.confirmReset ? `<div class="danger"><h3>Start a new stewardship?</h3><p>This permanently clears this browser’s city, treasury, and discoveries.</p><button data-action="reset-confirm">Reset save & start new game</button><button data-action="reset-cancel">Keep my city</button></div>` : '<button class="plain danger-text" data-action="reset-ask">New game / reset save</button>'}`;
      }
    }
    el.innerHTML = `<div class="panel-top"><span>${crest} TERRA · MUNICIPAL RECORDS</span><button data-action="close" aria-label="Close ledger">×</button></div><div class="panel-scroll">${body}</div><div class="panel-bottom"><span>♜ <b id="panel-crowns">${format(s.crowns)}</b> CROWNS AVAILABLE</span><small>ESC TO CLOSE</small></div>`;
  }
  update(weather: string, fps: number, debug: boolean) { const e = this.economy; document.querySelector('#crowns')!.textContent = format(e.state.crowns); document.querySelector('#rate')!.textContent = '+' + e.rate.toFixed(1); document.querySelector('#stage')!.textContent = `${String(e.stage).padStart(2, '0')} / ${STAGES[e.stage].toUpperCase()}`;
    const objectives = ['Inspect the old Scrap Yard.', 'Collect the Scrap Yard’s first earnings.', 'Repair the sorting rig.', 'Restore the district boiler.', 'Bring light back to the streets.', `Build toward ${STAGES[Math.min(5, e.stage + 1)]}. Every commission changes Terra.`]; document.querySelector('#objective')!.textContent = objectives[e.state.objective]; const day = e.state.day; const hour = clock(day).hour; this.wardLine(); document.querySelector('#weather')!.textContent = `${weather === 'rain' ? 'DRIZZLE' : weather === 'fog' ? 'INDUSTRIAL FOG' : weather === 'clear' ? 'CLEAR SKIES' : 'OVERCAST'} · ${hour >= 6 && hour < 10 ? 'DAWN' : hour >= 10 && hour < 17 ? 'DAY' : hour >= 17 && hour < 21 ? 'DUSK' : 'NIGHT'}`;
    const angle = ((-this.player.yaw * 180 / Math.PI) % 360 + 360) % 360; document.querySelector('#compass')!.textContent = ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'][Math.round(angle / 45) % 8]; const target = this.player.target; const prompt = document.querySelector('#interaction')!; prompt.toggleAttribute('hidden', !target || !this.player.locked); if (target) prompt.innerHTML = `<kbd>E</kbd><span>${target.label}<small>${target.hint ?? (target.kind === 'property' ? 'OPEN PROPERTY LEDGER' : target.kind === 'discovery' ? 'EXAMINE DISCOVERY' : 'INTERACT')}</small></span>`;
    const tracked = document.querySelector('#tracked')!; tracked.toggleAttribute('hidden', !this.tracked || !this.player.locked || !!target); if (this.tracked && this.player.locked) { const p = PROPERTIES.find(p => p.id === this.tracked)!; const dx = p.x - this.player.position.x; const dz = p.z - this.player.position.z; const distance = Math.hypot(dx, dz); const relative = Math.atan2(-dx, -dz) - this.player.yaw; tracked.innerHTML = `<span style="display:inline-block;transform:rotate(${-relative}rad)">↑</span> ${p.name} <small>${Math.floor(distance)} m</small>`; }
    document.querySelectorAll<HTMLButtonElement>('.purchase[data-cost]').forEach(b => { b.disabled = b.dataset.locked === 'true' || e.state.crowns < Number(b.dataset.cost); b.style.setProperty('--saved', Math.min(100, Math.floor(e.state.crowns / Number(b.dataset.cost) * 100)) + '%'); }); if (this.selected) { const p = e.state.properties[this.selected]; const collect = document.querySelector<HTMLButtonElement>('[data-action=collect]'); if (collect) { collect.disabled = p.stored < .1; collect.querySelector('b')!.textContent = format(p.stored) + ' ♜'; } const bar = document.querySelector<HTMLElement>('.production-bar span'); if (bar) bar.style.width = p.progress / PROPERTIES.find(v=>v.id === this.selected)!.interval * 100 + '%'; } const pc = document.querySelector('#panel-crowns'); if (pc) pc.textContent = format(e.state.crowns); const db = document.querySelector('#debug')!; db.toggleAttribute('hidden', !debug); if (debug) db.textContent = `${Math.round(fps)} FPS · ${this.player.position.x.toFixed(1)}, ${this.player.position.y.toFixed(1)}, ${this.player.position.z.toFixed(1)} · Tier ${e.stage}`;
  }
}
