import { clock, curfewNotice, districtAt, district, heatName, bandWord } from '../simulation/occupation';
import { HOME_TIERS, homeTier } from '../simulation/home';
import { OBJECTIVE } from '../simulation/intro';
import { HOLD } from '../simulation/resist';
import { Economy, PROPERTIES, INFRA, STAGES, TRAITS, OFFLINE, ANCHOR_CLUES, ANCHOR_CASE, format, type PropertyId, type InfraId, type SiteId } from '../simulation/economy';
import { Consignment } from '../world/logistics';
import { Vector3 } from 'three';
import type { Player } from '../player/controller';
import type { City, Target } from '../world/city';
import type { Soundscape } from '../audio/sound';
const crest = `<svg viewBox="0 0 40 48" aria-hidden="true"><path d="M4 3h32v26L20 44 4 29z"/><path d="M11 13h18m-9 0v20M13 19h14"/></svg>`;
/** The compass tape: three turns of the dial (so the heading can wrap), one label every 45 degrees. */
const K = 2; // pixels per degree on the tape
const COMPASS_LABELS = Array.from({ length: 25 }, (_, i) => { const d = i * 45, n = ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'][i % 8]; return `<span class="${n.length === 1 ? 'card' : ''}" style="left:${d * K}px">${n}</span>`; }).join('');
/** What the Steward notices. Short, and never an explanation. */
const LORE: Record<string, string> = { map: 'The Seven Provinces: Veyr sends iron; Orison sends salt. Terra once kept them all in motion.', automaton: 'A maker’s mark: FINCH, 1841. Its last instruction was “keep the lamps burning.”', shrine: '“No ember is too small.” The first engineers lit this flame when Terra was only a bridge.',
      archive: 'Record cylinders, shelved by a hand older than the brick around them. One label is still legible: “Lift ledger — all seven anchors holding.”', weathervane: 'A lens ringed in gold, sighted on the eastern isle. The Ordinance bricked up the door below and never found the way up.',
      hearth: 'Candle stubs and a row of names scratched small. The last one is fresh. Someone still comes here.', undergate: 'Ivory, fitted without a seam, and warm to the touch. Whatever is behind it is still running.',
      registry: 'Every household in the ward, with a column for PERMITTED and a column for WATCHED. One drawer has been left open, tied with a turquoise ribbon. Somebody inside is on your side.', packetlight: 'The signal book is still on its hook. The last entry: “Orison packet, on time. Lamp trimmed. Ordinance vessel, unannounced.” Nothing after it.', pigeons: 'Each bird wears a brass tag stamped with a ward number. Finch’s ledger of flights goes back further than the Ordinance does.', anchor: 'The clasp is older than the iron around it. III is stamped beneath a seven-point seal. It is holding.',
  survey: 'An Ordinance survey sheet. Seven marks along Terra’s keel, each labelled FOUNDATION STABILISER. Three are ringed. Stamped across the corner, twice: DO NOT LOAD.',
  studs: 'Through the glass: seven studs set round the Weathervane’s cap. Six are dull gold. The third is turquoise.',
  gate: 'Under the chains, cut into the lintel: ANCHOR V. Below it, smaller: TEND FROM BELOW.',
  collar: 'A casting pattern for a collar with seven lugs. The order slip reads REPLACEMENT, TO THE OLD GAUGE. Three castings lie cracked beside it.',
  sightline: 'Two brass sighting rings bolted to the rail. One holds the Weathervane’s cap. The other is tilted down, at nothing: cloud, below Terra’s rim.',
  chart: 'Seven lenses in a ring. The third burns steady. The fifth is faint. The rest are dark.',
  backwater: 'A length of ivory conduit, sawn through and used as a gutter. The cut end is warm.' };
export class Interface {
  app = document.querySelector<HTMLDivElement>('#app')!; started = false; panel: string | null = null; tab = 'Properties'; selected: PropertyId | null = null; tracked: PropertyId | null = 'scrap'; siteKey = ''; confirmReset = false; toastTimer = 0; hintOff = false; private hudH = 0;
  private aim = new Vector3(); private aimOn = false; private cam = new Vector3(); private view = { w: 0, h: 0, top: 0, bottom: 0, left: 0, right: 0, rib: 0, at: 0 }; private mk = { on: false, edge: false, text: '', pin: '', alpha: -1 };
  onStart: () => void = () => {}; onReset: () => void = () => {}; onQuality: () => void = () => {};
  constructor(public economy: Economy, public player: Player, public city: City, public sound: Soundscape) { this.app.innerHTML = `
    <header id="hud">
      <div class="identity">${crest}<div><span class="id-over">CITY TYCOON · TERRA</span><b id="ward-name">THE LOWWORKS</b></div></div>
      <div class="ribbon" role="group" aria-label="Compass, clock and ward">
        <div class="tape" aria-hidden="true"><div class="strip" id="strip">${COMPASS_LABELS}</div><i class="index"></i><i class="rb-pin" id="rb-pin" hidden></i></div>
        <div class="clockline"><span id="clock">17:16</span></div>
        <div class="meta"><span id="weather">DRIZZLE · DUSK</span><span id="curfew"></span><b id="ward" class="tag" data-band="heavy">HEAVY 80%</b></div>
      </div>
      <div class="treasury"><small>TREASURY</small><div class="amount"><span class="coin" aria-hidden="true">♜</span><strong id="crowns">35</strong></div><span class="income"><b id="rate">+0</b> Crowns / sec</span></div>
    </header>
    <div id="crosshair"></div><div id="interaction" hidden></div>
    <div id="marker" hidden aria-hidden="true"><i class="mk-chev"><svg viewBox="0 0 14 14"><path class="o" d="M4 1.5 10.5 7 4 12.5"/><path class="i" d="M4 1.5 10.5 7 4 12.5"/></svg></i><i class="mk-pin"></i><b class="mk-dist" id="mk-dist"></b></div>
    <div id="toast" role="status" aria-live="polite" aria-atomic="true"></div>
    <footer id="hud-bottom"><div class="objective"><span class="overline">A CITY WORTH SAVING</span><p id="objective">${OBJECTIVE}</p><div class="steps"><span id="step-no">STEP 1 / 6</span><span class="pips" id="pips" aria-hidden="true">${'<i></i>'.repeat(6)}</span><span id="stage">00 / THE LOWWORKS</span></div></div><div class="controls"><span><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> Walk</span><span><kbd>E</kbd> Interact</span><span><kbd>⇧</kbd> Sprint</span><button class="ledger-control" data-action="ledger"><kbd>TAB</kbd> Ledger</button></div></footer>
    <section id="welcome" class="welcome"><div class="eyebrow"><span></span> WORLD OF LOCKE · CHAPTER I</div><div class="title-stamp">A STEAMPUNK CITY TALE</div><h1 aria-label="Terra"><span>TER</span><span>RA<span class="title-dot">.</span></span></h1><p>A little soot. A little steam.<br>A whole city to bring back to life.</p><button id="enter" class="primary">${economy.state.playtime > 1 ? 'Continue stewardship' : 'Enter the Lowworks'} <span>↗</span></button><div class="welcome-foot">EXPLORE · RESTORE · WATCH IT GROW</div></section>
    <section id="pause" class="pause" hidden><div class="eyebrow">THE CITY KEEPS TURNING</div><h2>Take a breath.</h2><p>Your businesses continue working while you’re here.</p><button data-action="resume" class="primary">Return to Terra <span>↗</span></button><button data-action="ledger" class="plain">Open city ledger</button><button data-action="settings" class="plain">Settings</button></section>
    <aside id="panel" class="panel" hidden tabindex="-1" aria-label="City ledger"></aside><div id="debug" hidden></div><div id="save-status" role="status"></div>`;
    document.body.classList.toggle('reduced-motion', economy.state.settings.reducedMotion);
    document.querySelector('#enter')!.addEventListener('click', () => this.start());
    this.app.addEventListener('click', e => { const button = (e.target as HTMLElement).closest<HTMLElement>('[data-action]'); if (button && !button.hasAttribute('disabled')) this.action(button.dataset.action!, button.dataset.id ?? ''); });
    this.app.addEventListener('input', e => { const input = e.target as HTMLInputElement; const key = input.dataset.setting; if (!key) return; const s = this.economy.state.settings; if (key === 'reducedMotion') s.reducedMotion = input.checked; else if (['master', 'ambience', 'sfx', 'music', 'sensitivity'].includes(key)) (s as unknown as Record<string, number>)[key] = Number(input.value); document.body.classList.toggle('reduced-motion', s.reducedMotion); this.sound.apply(); this.economy.save(); });
    document.addEventListener('keydown', e => { if (!this.started || e.repeat) return; if (e.code === 'Tab' && !this.panel && this.player.locked && !document.body.classList.contains('scene')) { e.preventDefault(); this.openLedger(); } if (e.code === 'Escape' && this.panel) this.close(false); });
    // On a phone the ledger is a bottom sheet: pulling its header down closes it.
    let pull = -1; this.app.addEventListener('pointerdown', e => { pull = (e.target as HTMLElement).closest('.panel-top') && !(e.target as HTMLElement).closest('button') ? e.clientY : -1; }); this.app.addEventListener('pointerup', e => { if (pull >= 0 && e.clientY - pull > 70 && this.panel && matchMedia('(max-width:700px)').matches) this.close(true); pull = -1; });
    player.onInteract = t => this.interact(t); player.onLock = locked => { const pause = document.querySelector<HTMLElement>('#pause')!; pause.toggleAttribute('hidden', locked || !this.started || this.panel !== null); if (!pause.hidden) pause.querySelector<HTMLElement>('[data-action=resume]')?.focus({ preventScroll: true }); document.body.classList.toggle('playing', locked); };
  }
  start() { this.started = true; document.querySelector('#welcome')!.setAttribute('hidden', ''); document.body.classList.add('started'); this.sound.start(); this.onStart(); void this.player.lock(); if (this.economy.offlineAward > 2) this.toast(`Welcome home. Terra earned ${format(this.economy.offlineAward)} Crowns while you were away.`, 8000); else if (this.economy.state.intro.played && this.economy.state.objective === 0 && this.economy.state.resist.rook === 0) this.toast(`Terra has seen better years. ${OBJECTIVE}`); }
  /** The clock and the ward the Steward is standing in: both read the one game clock and the one occupation rule. */
  private ward = ''; private band = '';
  wardLine() { const e = this.economy, p = this.player.position, id = districtAt(p.x, p.z), pct = e.occupationOf(id), band = e.effects(id), key = e.band(id), notice = curfewNotice(e.state.day, key), name = district(id).name;
    this.put('clock', clock(e.state.day).text); const c = document.querySelector('#curfew')!; this.put('curfew', notice || (e.state.heat >= .5 ? heatName(e.state.heat).toUpperCase() : '')); c.classList.toggle('on', notice === 'CURFEW');
    this.put('ward-name', name.toUpperCase()); const tag = document.querySelector('#ward')!; this.put('ward', `${bandWord(key)} ${pct}%`); tag.setAttribute('data-band', key); tag.setAttribute('title', `${name} · Occupation ${pct}% · ${band.name}`);
    // Walking into a ward, or a ward changing under your feet, says what that means once. The street says the rest, and the ledger keeps it.
    if (this.started && (id !== this.ward || band.name !== this.band)) { const first = !this.ward; this.ward = id; this.band = band.name; if (!first) this.toast(`${band.name}. ${band.notes.join(' · ')}.`, 5200, `${name} · Occupation ${pct}%`); } }
  /** Write text only when it changed: the HUD is refreshed ten times a second and most of it stands still. */
  private put(id: string, text: string) { const el = document.getElementById(id)!; if (el.textContent !== text) el.textContent = text; }
  toast(message: string, duration = 4500, over = '') { const el = document.querySelector<HTMLElement>('#toast')!; el.replaceChildren(); if (over) { const o = document.createElement('span'); o.className = 't-over'; o.textContent = over; el.append(o); } el.append(message);
    el.classList.add('show'); document.body.classList.add('toasting'); clearTimeout(this.toastTimer); this.toastTimer = window.setTimeout(() => { el.classList.remove('show'); document.body.classList.remove('toasting'); }, duration); }
  openLedger(tab = this.tab) { this.panel = 'ledger'; this.tab = tab; this.selected = null; this.player.release(); document.querySelector('#pause')!.setAttribute('hidden', ''); this.render(); document.querySelector<HTMLButtonElement>('#panel [data-action=close]')?.focus(); }
  /** Home: a night's sleep passes the time to morning, pays what the trades pay unattended, and lets the patrols forget a little. */
  rest() { const r = this.economy.sleep(); if (!r) return this.toast('Too early to sleep. The room is yours all the same: nobody watches a Steward at home.', 6000);
    this.sound.collect(); this.toast(`You sleep ${r.hours} hours. Six in the morning; the curfew is lifted.${r.award >= 1 ? ` The trades brought in ${format(r.award)} Crowns overnight.` : ''}`, 9000); }
  answer() { const got = this.economy.signal(); if (!got) return; this.sound.purchase(); this.toast(`You turn the lamp up, twice. The Weathervane answers, and something crosses the roofs toward the cellar. +${format(got)} Crowns by morning.`, 9500); }
  /** E on the collection clerk: his word, and for the keeper the crate signed for. */
  clerk() { const say = this.city.presentation.rookYard.talk(); if (say) this.toast(say, 8000); }
  /** The bench at Rook & Son: the day's work, signed. It counts as reporting, exactly as the ledger does. */
  work() { this.economy.inspect('scrap'); this.sound.collect(); this.toast(HOLD.scrap!.signed, 8000); }
  onDoor: () => void = () => {};
  interact(t: Target) { if (t.kind === 'door') return this.onDoor(); if (t.kind === 'home') return this.rest(); if (t.kind === 'signal') return this.answer(); if (t.kind === 'resist') return t.id === 'rook.clerk' ? this.clerk() : this.work(); if (t.kind === 'property') { this.economy.inspect(t.id); this.selected = t.id as PropertyId; this.panel = 'property'; this.player.release(); this.render(); } else if (t.kind === 'lift') this.city.edge.startRide(this.player, t.id === 'lift.down'); else if (t.kind === 'ladder') { const l = this.city.ladders.find(l => l.id === t.id); if (l) this.player.climb(l); } else if (t.kind === 'ledger') this.openLedger(); else if (t.kind === 'district') this.openLedger('Districts'); else if (t.kind === 'site') { const load = Consignment.all.find(c => c.id === t.id), held = Consignment.carried(); if (load) this.carry(load); else if (held?.dest === t.id) this.deliver(held); else if (t.id.startsWith('finch.')) { const say = this.city.presentation.finchRun.use(t.id); if (say) this.toast(say, 8000); } else this.openSite(t.id); } else { const text = LORE[t.id] ?? '';
      if (this.economy.discover(t.id)) { this.sound.collect(); this.toast(`${text}  +55 Crowns · +3% income`, 9500); return; }
      // An observation is kept, not collected. If it changes what can be done, say so in one line.
      const before = this.economy.researchBlocker('anchors'), price = this.economy.charterCost('anchors'), fresh = this.economy.learn(t.id);
      if (!fresh) { this.toast(text, 7000); return; }
      this.sound.collect(); const after = this.economy.researchBlocker('anchors');
      const clue = (ANCHOR_CLUES as readonly string[]).includes(t.id), e = this.economy, wasCase = clue && before !== null && /rumour|Not yet/.test(before), isCase = e.state.knowledge.includes('anchor') && e.anchorClues >= ANCHOR_CASE; void after;
      const consequence = !clue ? '' : wasCase && isCase ? ' That is a case. The Finch Institute will hear it.' : t.id === 'survey' && e.charterCost('anchors') < price ? ' The Institute can work from their measurements.' : !isCase && e.state.knowledge.includes('anchor') ? ' The Institute will want more than this.' : '';
      this.toast(text + consequence, 9500); if (this.panel) this.render(); } }
  /** Logistics in the Steward's own arms: take the Foundry's cutters crate, and hand it over at the Finch cellar. */
  carry(load: Consignment) { if (load.carrying) { load.drop(); return this.toast('You set the crate back where it was.'); } this.toast(load.take() ?? load.taken, 8000); }
  /** Delivery happens where the goods are received; it is covert, so watching eyes there refuse it. */
  deliver(load: Consignment) { if (!load.site) { if (load.receive?.()) { load.drop(); this.sound.purchase(); } return; } const at = load.deliverAt.split('.')[0] as SiteId; if (this.city.watched(at)) return this.toast(this.economy.site(at).watched); if (this.economy.deliver(load.site)) { load.drop(); this.sound.purchase(); } }
  /** Physical places, not menus: each site's spots (a cellar door, a shift board, a spring,
   * a forge) carry their own steps. Covert spots refuse while occupation eyes are on you. */
  openSite(key: string) { const [id, name] = key.split('.') as [SiteId, string]; const s = this.economy.state, level = s.sites[id], site = this.economy.site(id), spot = site.spots[name];
    if (level < spot.from) return this.toast(spot.before, 8000);
    if (level > spot.to) return this.toast(spot.after, 7000);
    const closed = spot.closed?.(s); if (closed) return this.toast(closed);
    if (spot.covert && this.city.watched(id)) return this.toast(site.watched);
    this.siteKey = key; this.panel = 'site'; this.player.release(); this.render(); }
  close(resume = false) { this.panel = null; this.selected = null; this.confirmReset = false; document.querySelector('#panel')!.setAttribute('hidden', ''); if (resume) void this.player.lock(); else { const pause = document.querySelector<HTMLElement>('#pause')!; pause.removeAttribute('hidden'); pause.querySelector<HTMLElement>('[data-action=resume]')?.focus({ preventScroll: true }); } }
  action(action: string, id: string) {
    if (action === 'resume') { this.sound.start(); void this.player.lock(); }
    if (action === 'ledger') this.openLedger(); if (action === 'settings') this.openLedger('Settings'); if (action === 'close') this.close(true); if (action === 'tab') { this.tab = id; this.confirmReset = false; this.render(); document.querySelector<HTMLButtonElement>(`#panel [data-action=tab][data-id="${id}"]`)?.focus(); }
    if (action === 'track') { this.tracked = id as PropertyId; this.toast(`Follow the marker to ${PROPERTIES.find(p => p.id === id)!.name}.`); this.close(true); }
    if (action === 'collect') { const amount = this.economy.collect(id as PropertyId); if (amount > 0) { this.sound.collect(); this.toast(`Collected ${format(amount)} Crowns. Every small beginning matters.`); this.economy.save(); } this.render(); }
    if (action === 'upgrade') { if (this.economy.upgrade(id as PropertyId)) this.sound.purchase(); else this.toast('The treasury cannot cover that commission yet.'); this.render(); }
    if (action === 'automate') { if (this.economy.automate(id as PropertyId)) { this.sound.purchase(); this.toast('A foreman takes over. All production now reaches the treasury automatically.'); } this.render(); }
    if (action === 'site') { if (this.economy.advanceSite(id as SiteId)) { this.sound.purchase(); this.close(true); } else this.toast('The treasury cannot cover that yet.'); return; }
    if (action === 'infra') { if (this.economy.upgradeInfra(id as InfraId)) this.sound.purchase(); this.render(); }
    if (action === 'unlock') { if (this.economy.unlock(id)) { this.sound.purchase(); this.toast('Charter approved. The district gates are opening.'); } this.render(); }
    if (action === 'research') { if (this.economy.research(id)) this.sound.purchase(); this.render(); }
    if (action === 'reset-ask') { this.confirmReset = true; this.render(); } if (action === 'reset-cancel') { this.confirmReset = false; this.render(); }
    if (action === 'reset-confirm') { this.economy.reset(); this.onReset(); this.close(false); this.toast('A new stewardship begins.'); }
    if (action === 'quality') { this.economy.state.settings.quality = id as 'low' | 'high'; this.onQuality(); this.economy.save(); this.render(); }
    if (action === 'save') { this.economy.save(); this.toast('City records saved on this device.'); }
  }
  button(action: string, id: string, label: string, cost?: number, extraDisabled = false) { const disabled = extraDisabled || (cost !== undefined && this.economy.state.crowns < cost); const saved = cost ? Math.min(100, Math.floor(this.economy.state.crowns / cost * 100)) : 100; return `<button class="purchase" style="--saved:${saved}%" data-action="${action}" data-id="${id}" ${cost === undefined ? '' : `data-cost="${cost}"`} ${extraDisabled ? 'data-locked="true"' : ''} ${disabled ? 'disabled' : ''}><span>${label}</span><b>${cost === undefined ? '↗' : format(cost) + ' ♜'}</b></button>`; }
  render() { if (!this.panel) return; const el = document.querySelector<HTMLElement>('#panel')!; const opening = el.hasAttribute('hidden'); el.removeAttribute('hidden'); if (opening) el.focus({ preventScroll: true }); document.querySelector('#pause')!.setAttribute('hidden', '');
    let body = ''; const s = this.economy.state;
    if (this.panel === 'site') { const id = this.siteKey.split('.')[0] as SiteId, site = this.economy.site(id), level = s.sites[id], step = site.steps[level], blocker = this.economy.siteBlocker(id), busy = this.city.constructions.some(c => c.site === id);
      const voice = site.voice[step.kind];
      body = `<div class="overline">${voice[0]}</div><h2>${site.name}</h2><p class="description">${voice[1]}</p><div class="level-track">${site.steps.map((_, i) => `<span class="${i < level ? 'done' : ''}">${String(i + 1).padStart(2, '0')}</span>`).join('')}</div><div class="section-label">${step.kind === 'covert' ? 'QUIET WORK' : step.kind === 'liberation' ? 'OPEN RESISTANCE' : 'RESTORATION'}</div><h3>${step.name}</h3><p class="muted">${step.detail}${step.kind === 'liberation' ? ' Lifting the occupation levy raises city income by 15%.' : step.kind === 'restoration' ? ' The running spring adds another 10% to city income.' : ''}</p>${this.button('site', id, busy ? 'Work in progress…' : blocker ?? voice[2], this.economy.siteCost(id), !!blocker || busy)}`;
    } else if (this.panel === 'property' && this.selected) { const p = PROPERTIES.find(p => p.id === this.selected)!; const v = s.properties[p.id]; const constructing = this.city.constructions.some(c => Math.abs(c.group.position.x - p.x) < 1 && Math.abs(c.group.position.z - p.z) < 1);
      body = `<div class="overline">${p.kind} / LOWWORKS</div><h2>${p.name}</h2><p class="description">${p.description}</p><div class="level-track">${p.upgrades.map((_, i) => `<span class="${i < v.level ? 'done' : ''}">${String(i + 1).padStart(2, '0')}</span>`).join('')}</div><div class="instrument"><div><small>PRODUCTION</small><strong>${format(this.economy.output(p.id))} <em>♜</em></strong><span>every ${p.interval} seconds</span></div><div><small>CITY CONTRIBUTION</small><strong>${(this.economy.output(p.id) / p.interval * (v.automated ? 1 : .4)).toFixed(1)} <em>/s</em></strong><span>${v.automated ? 'Fully automated' : '40% passive · 60% on site'}</span></div></div><div class="production-bar"><span style="width:${v.progress / p.interval * 100}%"></span></div>`;
      // What this trade does for everything else: the reason to raise it ahead of its neighbours.
      { const t = TRAITS[p.id], pct = (n: number) => Math.round(t.per * n * 100); const worth = this.economy.traitWorth(p.id); body += `<p class="footnote"><b>${t.name.toUpperCase()}</b> · ${v.level ? `${pct(v.level)}% ${t.effect}` : `nothing yet`}${worth.now ? ` (${format(worth.now)} ♜ on the work still to do)` : ''}${v.level < 5 ? ` · next level: ${pct(v.level + 1)}%${worth.next ? `, worth about ${format(worth.next)} ♜ more` : ''}` : ''}</p>`; }
      if (!v.automated) body += this.button('collect', p.id, `Collect local earnings`, undefined, v.stored < .1).replace('↗</b>', `${format(v.stored)} ♜</b>`);
      body += `<div class="section-label">NEXT COMMISSION</div>`;
      if (v.level < 5) body += `<h3>${p.upgrades[v.level]}</h3><p class="muted">${v.level === 2 ? 'A major milestone: 50% production bonus and an expanded factory floor.' : v.level === 4 ? 'Masterwork milestone: double output and a luminous aether crown.' : 'Restore the property, raise production, and put Terra’s workers back to work.'} Construction takes ${this.economy.buildSeconds(v.level + 1)} seconds.</p>${this.button('upgrade', p.id, constructing ? 'Construction in progress…' : 'Commission improvement', this.economy.cost(p.id), constructing)}`;
      else body += '<h3>Masterwork property</h3><p class="muted">The pride of Terra. All five commissions are complete.</p>';
      body += `<div class="section-label">OPERATIONS</div>${v.automated ? '<p class="status-good">● Foreman on duty · all income deposited automatically</p>' : this.button('automate', p.id, 'Appoint a foreman', this.economy.foremanCost(p.id), v.level === 0)}<p class="footnote">${v.level === 0 ? 'Restore this business before appointing a foreman.' : 'Visit to collect reserves, or employ a foreman to handle every delivery.'}</p>`;
    } else {
      body = `<div class="overline">OFFICE OF THE CITY STEWARD</div><h2>The city ledger</h2><nav class="tabs" aria-label="Ledger sections">${['Properties', 'Infrastructure', 'Districts', 'Research', 'Home', 'Statistics', 'Settings'].map(t => `<button class="${this.tab === t ? 'active' : ''}" data-action="tab" data-id="${t}">${t}</button>`).join('')}</nav>`;
      if (this.tab === 'Properties') { body += `<p class="description">A thousand hands keep Terra turning.<br>Visit a property’s brass ledger to invest.</p>` + PROPERTIES.map(p => `<div class="ledger-row"><div><small>${p.kind} · ${s.properties[p.id].level}/5</small><h3>${p.name}</h3><p>${(this.economy.output(p.id) / p.interval).toFixed(1)} ♜/s potential ${s.properties[p.id].automated ? '· AUTOMATED' : ''}</p></div><button class="find" data-action="track" data-id="${p.id}" aria-label="Find ${p.name}">↗</button></div>`).join(''); }
      if (this.tab === 'Infrastructure') body += `<p class="description">The things a city shares. Every improvement makes the whole district stronger.</p>` + INFRA.map(i => `<div class="ledger-row block"><small>CIVIC WORKS · ${s.infrastructure[i.id]}/3</small><h3>${i.name}</h3><p>${i.detail}</p><p class="status-good">${i.effect}</p>${s.infrastructure[i.id] < 3 ? this.button('infra', i.id, 'Commission level ' + (s.infrastructure[i.id] + 1), this.economy.infraCost(i.id), this.city.constructions.some(c => c.group.position.x === 0)) : '<span class="complete">FULLY RESTORED</span>'}</div>`).join('');
      if (this.tab === 'Districts') body += `<div class="map"><svg viewBox="0 0 400 240" role="img" aria-label="Map: Lowworks in the center, Canal Ward east, Aether Heights north"><path d="M200 215V40M115 80H290M115 140H315M315 35v180" fill="none" stroke="#8f835d" stroke-width="3"/><path d="M282 0v240" stroke="#497773" stroke-width="12"/><g fill="#345150" stroke="#8f835d"><rect x="135" y="95" width="40" height="30"/><rect x="220" y="95" width="40" height="30"/><rect x="135" y="155" width="40" height="35"/><rect x="220" y="155" width="40" height="35"/><circle cx="200" cy="57" r="10"/></g><g fill="#ddcc9f" font-size="10" font-family="Georgia" text-anchor="middle"><text x="200" y="232">ARRIVAL</text><text x="200" y="18">AETHER HEIGHTS</text><text x="200" y="87">LOWWORKS</text><text x="344" y="129">CANAL</text><text x="344" y="143">WARD</text></g><circle cx="${200 + this.player.position.x * 1.5}" cy="${105 + this.player.position.z * 1.5}" r="4" fill="#f6d897"/></svg></div>` + [{ id: 'canal', name: 'The Canal Ward', desc: 'Cross the restored bridge into the trading quarter. +25% city income.', cost: this.economy.charterCost('canal'), stage: 1 }, { id: 'heights', name: 'Aether Heights', desc: 'Beyond the clock tower, the institute waits for a new age. +25% city income.', cost: this.economy.charterCost('heights'), stage: 3 }].map(d => `<div class="ledger-row block"><small>EXPANSION CHARTER</small><h3>${d.name}</h3><p>${d.desc}</p>${s.districts.includes(d.id) ? '<span class="complete">GATES OPEN</span>' : this.button('unlock', d.id, this.economy.stage < d.stage ? `Requires ${STAGES[d.stage]}` : 'Approve the charter', d.cost, this.economy.stage < d.stage)}</div>`).join('');
      if (this.tab === 'Research') { const e = this.economy, list = [
        { id: 'governors', name: 'Precision governors', desc: 'A steady engine wastes less work. Flyball governors on the Great Main, and the civic engineers build in half the time.' },
        { id: 'aether', name: 'Aether induction', desc: 'The light in the old shrine can be harnessed. The old works take it back: the garden fountain, the cistern, the sealed gate, and the Weathervane answers the eastern isle.' },
        { id: 'charter', name: 'The Seven Provinces charter', desc: 'Unite Locke’s merchants under the seal of Terra. Their colours fly over the main street and their traders set up in the square.' },
        // Not offered on prosperity alone: it appears once the Steward has seen something to ask about.
        ...(e.anchorClues > 0 || s.research.includes('anchors') ? [{ id: 'anchors', name: 'The Anchor survey', desc: s.knowledge.includes('survey') ? 'Something is clasped round the ribs under Terra. The Ordinance has already measured it; the Institute can start from their figures.' : 'Something is clasped round the ribs under Terra. Measure it properly, and find out what it is holding.' }] : [])];
        body += `<p class="description">The Finch Institute’s applied sciences.<br>Each raises city output by 25%, and each changes something you can go and see.</p>` + list.map(r => { const blocker = e.researchBlocker(r.id); return `<div class="ledger-row block"><small>${r.id === 'anchors' ? `FIELD SURVEY · ${Math.min(e.anchorClues, ANCHOR_CASE)} OF ${ANCHOR_CASE} OBSERVATIONS` : 'APPLIED SCIENCE'}</small><h3>${r.name}</h3><p>${r.desc}</p>${s.research.includes(r.id) ? '<span class="complete">RESEARCH COMPLETE</span>' : this.button('research', r.id, blocker ?? (r.id === 'anchors' ? 'Fund the survey' : 'Fund the research'), e.charterCost(r.id), !!blocker)}</div>`; }).join(''); }
      if (this.tab === 'Home') { const now = homeTier(s.home.level); body += `<div class="city-stage"><span>YOUR HOME</span><h3>${now.name}</h3><p>${now.desc}</p></div>` + HOME_TIERS.slice(s.home.level + 1).map(t => `<div class="ledger-row block"><small>HOME · NEXT</small><h3>${t.name}</h3><p>${t.desc}</p>${this.button('home', t.id, 'Not yet available', t.cost, true)}</div>`).join('') + '<p class="footnote">Your rooms are a promise, not yet a plan.</p>'; }
      if (this.tab === 'Statistics') { const e = this.economy, p = this.player.position, id = districtAt(p.x, p.z), band = e.effects(id); body += `<div class="section-label">WARD STATUS</div>` + [['Ward', district(id).name], ['Occupation', `${e.occupationOf(id)}% · ${band.name}`], ['Enforced', band.notes.join(' · ')]].map(([a, b]) => `<div class="stat-row"><span>${a}</span><b>${b}</b></div>`).join('');
      body += `<div class="section-label">THE CITY</div><div class="city-stage"><span>PROSPERITY ${this.economy.stage} / 5</span><h3>${STAGES[this.economy.stage]}</h3><p>${this.economy.investment} civic & business commissions</p></div>` + [['Treasury', `${format(s.crowns)} Crowns`], ['Lifetime earnings', `${format(s.earned)} Crowns`], ['Passive income', `${this.economy.rate.toFixed(2)} / second`], ['City production multiplier', `${this.economy.multiplier.toFixed(2)}×`], ['Stewardship time', `${Math.floor(s.playtime / 60)} minutes`], ['District charters', `${s.districts.length} / 2`], ['Discoveries', `${s.discoveries.length} / 3`], ['Dividends while away', `${Math.round(this.economy.awayShare * 100)}% · up to ${OFFLINE.hours} hours`]].map(([a, b]) => `<div class="stat-row"><span>${a}</span><b>${b}</b></div>`).join('') + '<p class="footnote">Unstaffed properties pay 40% directly and reserve 60% for on-site collection. Foremen automate the full output. Offline income includes automatic dividends only.</p>'; }
      if (this.tab === 'Settings') { body += '<p class="description">Make yourself at home in Terra.</p>'; for (const [key, label] of [['master', 'Master volume'], ['ambience', 'City ambience'], ['sfx', 'Effects & footsteps'], ['sensitivity', 'Mouse sensitivity']] as const) body += `<label class="slider"><span>${label}</span><input type="range" min="${key === 'sensitivity' ? '.2' : '0'}" max="${key === 'sensitivity' ? '2' : '1'}" step=".05" value="${s.settings[key]}" data-setting="${key}"/></label>`;
        body += `<p class="footnote">Original synthesized city soundscape. No music track is used.</p><label class="check"><input type="checkbox" data-setting="reducedMotion" ${s.settings.reducedMotion ? 'checked' : ''}/> Reduced motion · calm camera & transitions</label><p class="footnote">Your device’s reduced-motion preference is also respected.</p><div class="section-label">RENDER QUALITY</div><div class="quality">${['high', 'low'].map(q => `<button data-action="quality" data-id="${q}" class="${s.settings.quality === q ? 'active' : ''}">${q === 'high' ? 'Full atmosphere' : 'Performance'}</button>`).join('')}</div><div class="section-label">CITY RECORDS</div>${this.button('save', '', 'Save now')}<p class="footnote">Autosaved every 10 seconds and when you invest. Stored locally in this browser.</p>${this.confirmReset ? `<div class="danger"><h3>Start a new stewardship?</h3><p>This permanently clears this browser’s city, treasury, and discoveries.</p><button data-action="reset-confirm">Reset save & start new game</button><button data-action="reset-cancel">Keep my city</button></div>` : '<button class="plain danger-text" data-action="reset-ask">New game / reset save</button>'}`;
      }
    }
    el.innerHTML = `<div class="panel-top"><span>${crest} TERRA · MUNICIPAL RECORDS</span><button data-action="close" aria-label="Close ledger">×</button></div><div class="panel-scroll">${body}</div><div class="panel-bottom"><span>♜ <b id="panel-crowns">${format(s.crowns)}</b> CROWNS AVAILABLE</span><small>ESC TO CLOSE</small></div>`;
  }
  /** Where the HUD may put a marker (18 px of extra top margin: the chevron reaches about 30 px past the diamond): clear of the top plates, the toast, the objective card on a phone and the thumb buttons. */
  private measure() { const v = this.view, w = innerWidth, h = innerHeight; const now = performance.now(); if (v.w === w && v.h === h && now - v.at < 500) return; v.w = w; v.h = h; v.at = now;
    const edge = (sel: string) => document.querySelector<HTMLElement>(sel)?.getBoundingClientRect(), touch = document.body.classList.contains('touch');
    let top = (edge('#hud')?.bottom ?? 0) + 14; const toast = document.body.classList.contains('toasting') ? edge('#toast') : undefined; if (toast) top = Math.max(top, toast.bottom + 10);
    const card = touch ? edge('.objective') : undefined; if (card) top = Math.max(top, card.bottom + 12);
    v.top = top + 18; v.bottom = h - (touch ? 150 : 128); v.left = 36; v.right = w - (touch ? 104 : 36); if (v.bottom < v.top + 40) v.bottom = v.top + 40; v.rib = document.querySelector<HTMLElement>('#hud .tape')?.clientWidth ?? 0; const hh = Math.round(edge('#hud')?.height ?? 0); if (hh && hh !== this.hudH) { this.hudH = hh; document.documentElement.style.setProperty('--hud-h', hh + 'px'); } }
  /** Every frame, transforms only: the compass tape turns with the heading, and the tracked target is drawn on the ribbon and in the world
   * as a small ink diamond with its distance. Off screen (or behind) it parks on the edge of the safe area with a chevron pointing the way. */
  hudFrame() { if (!this.started) return; const cam = this.player.camera, m = this.mk, v = this.view; if (!v.w) this.measure();
    const heading = ((-this.player.yaw * 180 / Math.PI) % 360 + 360) % 360, strip = document.getElementById('strip')!, pin = document.getElementById('rb-pin')!, el = document.getElementById('marker')!;
    strip.style.transform = `translate3d(${-(360 + heading) * K}px,0,0)`;
    if (!this.aimOn) { if (m.on) { m.on = false; el.hidden = true; pin.hidden = true; } return; }
    if (!m.on) { m.on = true; el.hidden = false; pin.hidden = false; }
    const dx = this.aim.x - this.player.position.x, dz = this.aim.z - this.player.position.z, dist = Math.hypot(dx, dz);
    // The ribbon pin: the bearing of the target against the heading, parked at either end when it is round the back.
    const rel = ((Math.atan2(dx, -dz) * 180 / Math.PI - heading + 540) % 360) - 180, half = Math.max(0, v.rib / 2 - 10), px = Math.max(-half, Math.min(half, rel * K)), side = Math.abs(rel * K) > half ? (rel < 0 ? 'l' : 'r') : '';
    pin.style.transform = `translate3d(${px}px,0,0)`; if (m.pin !== side) { m.pin = side; if (side) pin.dataset.side = side; else delete pin.dataset.side; }
    // The world marker, in camera space so that "behind" is exact.
    const c = this.cam.copy(this.aim).applyMatrix4(cam.matrixWorldInverse), e = cam.projectionMatrix.elements, front = c.z < -.05; let sx = 0, sy = 0, edge = true;
    if (front) { sx = (e[0] * c.x / -c.z * .5 + .5) * v.w; sy = (-e[5] * c.y / -c.z * .5 + .5) * v.h; edge = sx < v.left || sx > v.right || sy < v.top || sy > v.bottom; }
    let angle = 0;
    if (edge) { let ux = front ? sx - v.w / 2 : c.x, uy = front ? sy - v.h / 2 : -c.y; if (Math.abs(ux) + Math.abs(uy) < 1e-4) uy = 1; const n = Math.hypot(ux, uy); ux /= n; uy /= n;
      const cx = v.w / 2, cy = v.h / 2, tx = ux > 0 ? (v.right - cx) / ux : ux < 0 ? (v.left - cx) / ux : Infinity, ty = uy > 0 ? (v.bottom - cy) / uy : uy < 0 ? (v.top - cy) / uy : Infinity, k = Math.min(tx, ty); sx = cx + ux * k; sy = cy + uy * k; angle = Math.atan2(uy, ux); }
    const scale = edge ? .9 : Math.max(.7, Math.min(1.15, 1.2 - dist / 140)), alpha = dist < 3 ? 0 : dist < 6 ? (dist - 3) / 3 : edge ? .95 : Math.max(.55, 1 - dist / 260);
    el.style.transform = `translate3d(${sx.toFixed(1)}px,${sy.toFixed(1)}px,0) scale(${scale.toFixed(3)})`; if (Math.abs(alpha - m.alpha) > .01) { m.alpha = alpha; el.style.opacity = alpha.toFixed(2); }
    if (m.edge !== edge) { m.edge = edge; el.classList.toggle('edge', edge); }
    if (edge) (el.firstElementChild as HTMLElement).style.transform = `rotate(${angle.toFixed(3)}rad) translateX(22px)`;
    const text = `${Math.floor(dist)} m`; if (text !== m.text) { m.text = text; document.getElementById('mk-dist')!.textContent = text; } }
  update(weather: string, fps: number, debug: boolean) { const e = this.economy; this.put('crowns', format(e.state.crowns)); this.put('rate', '+' + e.rate.toFixed(1)); this.put('stage', `${String(e.stage).padStart(2, '0')} / ${STAGES[e.stage].toUpperCase()}`); if (!this.hintOff && this.player.moved > 40) { this.hintOff = true; document.body.classList.add('hint-off'); }
    const objectives = [OBJECTIVE, 'Collect the Scrap Yard’s first earnings.', 'Repair the sorting rig.', 'Restore the district boiler.', 'Bring light back to the streets.', `Build toward ${STAGES[Math.min(5, e.stage + 1)]}. Every commission changes Terra.`]; this.put('objective', Consignment.carried()?.line || objectives[e.state.objective]); this.put('step-no', `STEP ${e.state.objective + 1} / ${objectives.length}`); document.querySelectorAll('#pips i').forEach((pip, i) => pip.classList.toggle('on', i <= e.state.objective)); const day = e.state.day; const hour = clock(day).hour; this.wardLine(); this.put('weather', `${weather === 'rain' ? 'DRIZZLE' : weather === 'fog' ? 'INDUSTRIAL FOG' : weather === 'clear' ? 'CLEAR SKIES' : 'OVERCAST'} · ${hour >= 6 && hour < 10 ? 'DAWN' : hour >= 10 && hour < 17 ? 'DAY' : hour >= 17 && hour < 21 ? 'DUSK' : 'NIGHT'}`);
    const target = this.player.target; const prompt = document.querySelector('#interaction')!; prompt.toggleAttribute('hidden', !target || !this.player.locked); if (target) prompt.innerHTML = `<kbd>E</kbd><span>${target.label}<small>${target.hint ?? (target.kind === 'property' ? 'OPEN PROPERTY LEDGER' : target.kind === 'discovery' ? 'EXAMINE DISCOVERY' : 'INTERACT')}</small></span>`;
    // The tracked target: the data is the same as ever (a property the Steward chose to follow); hudFrame() draws it every frame.
    const carrying = Consignment.carried()?.id === 'rook.crate'; const t = this.tracked && this.player.locked && !target && !carrying ? PROPERTIES.find(p => p.id === this.tracked) ?? null : null;
    if (t) this.aim.set(t.x, this.city.groundHeight(t.x, t.z) + 5, t.z); this.aimOn = !!t; this.measure();
    document.querySelectorAll<HTMLButtonElement>('.purchase[data-cost]').forEach(b => { b.disabled = b.dataset.locked === 'true' || e.state.crowns < Number(b.dataset.cost); b.style.setProperty('--saved', Math.min(100, Math.floor(e.state.crowns / Number(b.dataset.cost) * 100)) + '%'); }); if (this.selected) { const p = e.state.properties[this.selected]; const collect = document.querySelector<HTMLButtonElement>('[data-action=collect]'); if (collect) { collect.disabled = p.stored < .1; collect.querySelector('b')!.textContent = format(p.stored) + ' ♜'; } const bar = document.querySelector<HTMLElement>('.production-bar span'); if (bar) bar.style.width = p.progress / PROPERTIES.find(v=>v.id === this.selected)!.interval * 100 + '%'; } const pc = document.querySelector('#panel-crowns'); if (pc) pc.textContent = format(e.state.crowns); const db = document.querySelector('#debug')!; db.toggleAttribute('hidden', !debug); if (debug) db.textContent = `${Math.round(fps)} FPS · ${this.player.position.x.toFixed(1)}, ${this.player.position.y.toFixed(1)}, ${this.player.position.z.toFixed(1)} · Tier ${e.stage}`;
  }
}
