import * as T from 'three';
import { random, mats } from './assets';
import type { City } from './city';
export class Atmosphere {
  sun: T.DirectionalLight; hemi: T.HemisphereLight; rain: T.Points; smoke: T.Points; steam: T.Points; weather: 'rain' | 'overcast' | 'fog' = 'rain'; override: string | null = null;
  rainPositions = new Float32Array(1500 * 3); smokePositions = new Float32Array(220 * 3); steamPositions = new Float32Array(90 * 3); age = new Float32Array(220); steamAge = new Float32Array(90); sky = new T.Color();
  constructor(public scene: T.Scene, public city: City) {
    scene.fog = new T.FogExp2('#68787b', .011); scene.background = new T.Color('#71858b');
    this.hemi = new T.HemisphereLight('#b4c8cf', '#504433', 2); scene.add(this.hemi); this.sun = new T.DirectionalLight('#f4cd9a', 2.3); this.sun.position.set(-35, 55, 20); this.sun.castShadow = true; this.sun.shadow.mapSize.set(2048, 2048); this.sun.shadow.camera.left = -65; this.sun.shadow.camera.right = 65; this.sun.shadow.camera.top = 85; this.sun.shadow.camera.bottom = -60; this.sun.shadow.camera.far = 190; this.sun.shadow.normalBias = .04; this.sun.shadow.bias = -.0003; scene.add(this.sun); scene.add(this.sun.target);
    for (let i = 0; i < 1500; i++) { this.rainPositions[i * 3] = (random() - .5) * 100; this.rainPositions[i * 3 + 1] = random() * 40; this.rainPositions[i * 3 + 2] = (random() - .5) * 100; }
    const rg = new T.BufferGeometry(); rg.setAttribute('position', new T.BufferAttribute(this.rainPositions, 3)); this.rain = new T.Points(rg, new T.PointsMaterial({ color: '#b3cacf', size: .035, transparent: true, opacity: .42, depthWrite: false })); this.rain.frustumCulled = false; scene.add(this.rain);
    const canvas = document.createElement('canvas'); canvas.width = canvas.height = 64; const c = canvas.getContext('2d')!; const grad = c.createRadialGradient(32, 32, 0, 32, 32, 32); grad.addColorStop(0, 'rgba(255,255,255,.6)'); grad.addColorStop(.45, 'rgba(255,255,255,.26)'); grad.addColorStop(1, 'rgba(255,255,255,0)'); c.fillStyle = grad; c.fillRect(0, 0, 64, 64); const texture = new T.CanvasTexture(canvas);
    const sg = new T.BufferGeometry(); sg.setAttribute('position', new T.BufferAttribute(this.smokePositions, 3)); this.smoke = new T.Points(sg, new T.PointsMaterial({ color: '#5f6967', map: texture, size: 5.5, transparent: true, opacity: .4, depthWrite: false })); this.smoke.frustumCulled = false; scene.add(this.smoke); for (let i = 0; i < 220; i++) this.age[i] = random() * 15;
    const steamG = new T.BufferGeometry(); steamG.setAttribute('position', new T.BufferAttribute(this.steamPositions, 3)); this.steam = new T.Points(steamG, new T.PointsMaterial({ color: '#c7d9d6', map: texture, size: 1.4, transparent: true, opacity: .3, depthWrite: false })); scene.add(this.steam); this.steam.frustumCulled = false; for (let i = 0; i < 90; i++) this.steamAge[i] = random() * 5;
  }
  update(dt: number, time: number, camera: T.Camera) {
    const day = this.city.economy.state.day; const phase = Math.sin(day * Math.PI * 2 - Math.PI / 2); const daylight = T.MathUtils.smoothstep(phase, -.25, .7); const weather = this.override ?? (Math.floor(time / 110) % 3 === 0 ? 'rain' : Math.floor(time / 110) % 3 === 1 ? 'overcast' : 'fog'); this.weather = weather as typeof this.weather; const stage = this.city.economy.stage;
    this.sky.set('#24354f').lerp(new T.Color(stage >= 3 ? '#90c3d5' : '#879fac'), daylight); this.scene.background = this.sky; const fog = this.scene.fog as T.FogExp2; fog.color.copy(this.sky); fog.density = (weather === 'fog' ? .016 : .009) - stage * .0007; this.hemi.intensity = 1.9 + daylight * 1.1; this.sun.intensity = .55 + daylight * 2; this.sun.color.set(daylight > .4 ? '#f5d2a1' : '#9ab9e4'); this.sun.position.set(Math.cos(day * Math.PI * 2) * 55, 25 + Math.max(0, phase) * 55, 20); mats.glow.emissiveIntensity = 1.3 - daylight * .7;
    this.city.lamps.forEach((lamp, i) => { lamp.intensity = (5 + this.city.economy.state.infrastructure.lamps * 12) * (1 - daylight * .65) * (stage === 0 && i === 0 ? .6 + Math.sin(time * 13) * .35 : 1); lamp.color.set(this.city.economy.state.infrastructure.lamps === 3 ? '#76e6d2' : '#ffbf6c'); });
    this.rain.visible = weather === 'rain'; this.rain.position.set(camera.position.x, 0, camera.position.z); if (this.rain.visible) { for (let i = 0; i < 1500; i++) { const j = i * 3; this.rainPositions[j + 1] -= dt * (13 + i % 4); this.rainPositions[j] += dt * .7; if (this.rainPositions[j + 1] < 0) this.rainPositions[j + 1] = 40; } this.rain.geometry.attributes.position.needsUpdate = true; }
    for (let i = 0; i < 220; i++) { this.age[i] = (this.age[i] + dt) % 15; const a = this.age[i]; const o = this.city.smokeOrigins[i % 4]; this.smokePositions[i * 3] = o.x + a * .4 + Math.sin(i * 13 + a) * a * .1; this.smokePositions[i * 3 + 1] = o.y + a * .8; this.smokePositions[i * 3 + 2] = o.z + Math.cos(i * 9 + a * .5) * a * .12; } this.smoke.geometry.attributes.position.needsUpdate = true; (this.smoke.material as T.PointsMaterial).opacity = .4 - stage * .045;
    for (let i = 0; i < 90; i++) { this.steamAge[i] = (this.steamAge[i] + dt) % 5; const a = this.steamAge[i]; this.steamPositions[i * 3] = -8 + Math.sin(i + a) * a * .3; this.steamPositions[i * 3 + 1] = 7 + a * .7; this.steamPositions[i * 3 + 2] = [29, 3, -30][i % 3] + a * .25; } this.steam.geometry.attributes.position.needsUpdate = true; (this.steam.material as T.PointsMaterial).opacity = .3 / (1 + this.city.economy.state.infrastructure.steam);
  }
}
