import type { Settings } from '../simulation/economy';
export class Soundscape {
  context?: AudioContext; master?: GainNode; ambient?: GainNode; sfx?: GainNode; music?: GainNode; rainGain?: GainNode; machine?: PannerNode; nextBell = 0;
  constructor(public settings: () => Settings) {}
  start() { if (this.context) { void this.context.resume(); return; } const c = this.context = new AudioContext(); this.master = c.createGain(); this.master.connect(c.destination); this.ambient = c.createGain(); this.ambient.connect(this.master); this.sfx = c.createGain(); this.sfx.connect(this.master); this.music = c.createGain(); this.music.connect(this.master);
    const buffer = c.createBuffer(1, c.sampleRate * 4, c.sampleRate); const samples = buffer.getChannelData(0); let last = 0; for (let i = 0; i < samples.length; i++) { last = (last + (Math.random() * 2 - 1) * .03) / 1.02; samples[i] = last * 3; }
    const noise = c.createBufferSource(); noise.buffer = buffer; noise.loop = true; const filter = c.createBiquadFilter(); filter.type = 'lowpass'; filter.frequency.value = 750; this.rainGain = c.createGain(); this.rainGain.gain.value = .17; noise.connect(filter); filter.connect(this.rainGain); this.rainGain.connect(this.ambient); noise.start();
    const motor = c.createOscillator(); motor.type = 'triangle'; motor.frequency.value = 48; const gain = c.createGain(); gain.gain.value = .045; this.machine = c.createPanner(); this.machine.panningModel = 'HRTF'; this.machine.distanceModel = 'inverse'; this.machine.refDistance = 7; this.machine.maxDistance = 70; this.machine.positionX.value = 12; this.machine.positionZ.value = 40; motor.connect(gain); gain.connect(this.machine); this.machine.connect(this.ambient); motor.start(); this.apply(); }
  apply() { if (!this.context) return; const s = this.settings(); this.master!.gain.value = s.master; this.ambient!.gain.value = s.ambience; this.sfx!.gain.value = s.sfx; this.music!.gain.value = s.music; }
  tone(freq: number, duration: number, volume = .1, type: OscillatorType = 'sine', delay = 0) { if (!this.context) return; const c = this.context; const t = c.currentTime + delay; const o = c.createOscillator(); const g = c.createGain(); o.type = type; o.frequency.setValueAtTime(freq, t); g.gain.setValueAtTime(0, t); g.gain.linearRampToValueAtTime(volume, t + .008); g.gain.exponentialRampToValueAtTime(.0001, t + duration); o.connect(g); g.connect(this.sfx!); o.start(t); o.stop(t + duration + .02); }
  purchase() { [261.63, 329.63, 392, 523.25].forEach((f, i) => this.tone(f, .55, .09, 'triangle', i * .07)); }
  collect() { this.tone(880, .2, .04); this.tone(1320, .3, .025, 'sine', .08); }
  step() { this.tone(65 + Math.random() * 35, .07, .05, 'triangle'); }
  hammer() { this.tone(180 + Math.random() * 70, .06, .045, 'square'); }
  update(x: number, z: number, yaw: number, raining: boolean, time: number) { if (!this.context) return; const l = this.context.listener; if (l.positionX) { l.positionX.value = x; l.positionY.value = 1.75; l.positionZ.value = z; l.forwardX.value = -Math.sin(yaw); l.forwardY.value = 0; l.forwardZ.value = -Math.cos(yaw); l.upX.value = 0; l.upY.value = 1; l.upZ.value = 0; } this.rainGain!.gain.setTargetAtTime(raining ? .2 : .055, this.context.currentTime, 1); if (time > this.nextBell) { this.nextBell = time + 90; this.tone(196, 3, .035); this.tone(392, 2.2, .012, 'sine', .1); } }
}
